### ISSUE TITLE
multiple definitions have same name in polymer serve v0.3.0

### ISSUE THREAD

**Issue by kaycebasques** [Polymer/polymer-cli#118]
Working in top-level directory of a fresh app project: 

```
polymer --version
0.3.0
polymer serve
Caught exception: DUPLICATE_NAME: Two or more option definitions have the same name
DUPLICATE_NAME: Two or more option definitions have the same name
    at halt (/Users/kayce/.nvm/versions/node/v4.4.3/lib/node_modules/polymer-cli/node_modules/command-line-args/lib/definitions.js:146:15)
    at Definitions.validate (/Users/kayce/.nvm/versions/node/v4.4.3/lib/node_modules/polymer-cli/node_modules/command-line-args/lib/definitions.js:80:7)
    at new Definitions (/Users/kayce/.nvm/versions/node/v4.4.3/lib/node_modules/polymer-cli/node_modules/command-line-args/lib/definitions.js:19:10)
    at new CommandLineArgs (/Users/kayce/.nvm/versions/node/v4.4.3/lib/node_modules/polymer-cli/node_modules/command-line-args/lib/command-line-args.js:43:24)
    at commandLineArgs (/Users/kayce/.nvm/versions/node/v4.4.3/lib/node_modules/polymer-cli/node_modules/command-line-args/lib/command-line-args.js:146:10)
    at CommandLineCommands.parse (/Users/kayce/.nvm/versions/node/v4.4.3/lib/node_modules/polymer-cli/node_modules/command-line-commands/lib/command-line-commands.js:76:19)
    at PolymerCli.run (/Users/kayce/.nvm/versions/node/v4.4.3/lib/node_modules/polymer-cli/lib/polymer-cli.js:83:35)
    at /Users/kayce/.nvm/versions/node/v4.4.3/lib/node_modules/polymer-cli/bin/polymer.js:21:7
    at /Users/kayce/.nvm/versions/node/v4.4.3/lib/node_modules/polymer-cli/node_modules/resolve/lib/async.js:46:14
    at process (/Users/kayce/.nvm/versions/node/v4.4.3/lib/node_modules/polymer-cli/node_modules/resolve/lib/async.js:173:43)
```

**Comment by justinfagnani** [comment]
Fixed in #113
