### ISSUE TITLE
`polymer init application && polymer build` = error

### ISSUE THREAD

**Issue by FredKSchott** [Polymer/polymer-cli#124]
I get:
```
error [Error: Invalid glob argument: ,/Users/fschott/Code/polytool-test/**/*,!build,!build/**/*,!bower_components,!bower_components/**/*,!node_modules,!node_modules/**/*]
Error: Invalid glob argument: ,/Users/fschott/Code/polytool-test/**/*,!build,!build/**/*,!bower_components,!bower_components/**/*,!node_modules,!node_modules/**/*
    at Object.src (/Users/fschott/Code/polytool/node_modules/vinyl-fs/lib/src/index.js:32:11)
    at /Users/fschott/Code/polytool/lib/build/build.js:73:33
    at new Promise (/Users/fschott/Code/polytool/node_modules/core-js/modules/es6.promise.js:193:7)
    at build (/Users/fschott/Code/polytool/lib/build/build.js:28:12)
    at BuildCommand.run (/Users/fschott/Code/polytool/lib/commands/build.js:45:16)
    at PolymerCli.run (/Users/fschott/Code/polytool/lib/polymer-cli.js:152:17)
    at /Users/fschott/Code/polytool/bin/polymer.js:22:7
    at /Users/fschott/Code/polytool/node_modules/resolve/lib/async.js:46:14
    at process (/Users/fschott/Code/polytool/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/fschott/Code/polytool/node_modules/resolve/lib/async.js:188:17)
```

Error message should be friendlier.

**Comment by azakus** [comment]
Seems fixed as of #136
