### ISSUE TITLE
polymer init > shop, ENOENT: no such file or directory, open 'token'

### ISSUE THREAD

**Issue by robdodson** [Polymer/polymer-cli#127]
Full trace

```
❯ polymer init
? Choose a template to initialize this folder with no description
info: [cli.init]    Running template shop
error: [cli.main]   Promise rejection: Error: ENOENT: no such file or directory, open 'token'
error: [cli.main]   Error: ENOENT: no such file or directory, open 'token'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at Function.tokenFromFile (/Users/robdodson/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/lib/github/github.js:33:19)
    at new Github (/Users/robdodson/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/lib/github/github.js:19:50)
    at new PolykartGenerator (/Users/robdodson/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/lib/templates/polykart.js:21:28)
    at Environment.instantiate (/Users/robdodson/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/node_modules/yeoman-environment/lib/environment.js:328:10)
    at Environment.create (/Users/robdodson/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/node_modules/yeoman-environment/lib/environment.js:305:15)
    at Environment.run (/Users/robdodson/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/node_modules/yeoman-environment/lib/environment.js:364:24)
    at runGenerator (/Users/robdodson/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/lib/commands/init.js:45:29)
```

**Comment by robdodson** [comment]
Btw it seems weird to choose a template "basic or shop" and then if you choose basic it asks you to choose "application or element".

**Comment by justinfagnani** [comment]
Right now this template requires a github token with access to repos in a file names `token`. This is temporary.

**Comment by justinfagnani** [comment]
Regarding the basic/shop, and the element/application split, I agree. This is a result of the basic generator being just one generator, which then prompts for a style of project. I think I'm going to split that generator, as well as bring it into the polymer-cli repo so it's easier to iterate on.
