### ISSUE TITLE
`polymer init shop` and `polymer init prpl-demo` throw errors

### ISSUE THREAD

**Issue by kaycebasques** [Polymer/polymer-cli#135]
prpl-demo:
```
polymer init prpl-demo
info: [cli.init]    Running template prpl-demo
error { [Error: ENOENT: no such file or directory, open 'token'] errno: -2, code: 'ENOENT', syscall: 'open', path: 'token' }
Error: ENOENT: no such file or directory, open 'token'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Function.tokenFromFile (/Users/kayce/.nvm/versions/node/v4.4.3/lib/node_modules/polymer-cli/lib/github/github.js:33:19)
    at new Github (/Users/kayce/.nvm/versions/node/v4.4.3/lib/node_modules/polymer-cli/lib/github/github.js:19:50)
    at new GithubGenerator (/Users/kayce/.nvm/versions/node/v4.4.3/lib/node_modules/polymer-cli/lib/init/github.js:21:28)
    at Environment.instantiate (/Users/kayce/.nvm/versions/node/v4.4.3/lib/node_modules/polymer-cli/node_modules/yeoman-environment/lib/environment.js:328:10)
    at Environment.create (/Users/kayce/.nvm/versions/node/v4.4.3/lib/node_modules/polymer-cli/node_modules/yeoman-environment/lib/environment.js:305:15)
    at Environment.run (/Users/kayce/.nvm/versions/node/v4.4.3/lib/node_modules/polymer-cli/node_modules/yeoman-environment/lib/environment.js:364:24)
    at runGenerator (/Users/kayce/.nvm/versions/node/v4.4.3/lib/node_modules/polymer-cli/lib/commands/init.js:60:29)
```
shop:
```
polymer init shop
info: [cli.init]    Running template shop
error { [Error: ENOENT: no such file or directory, open 'token'] errno: -2, code: 'ENOENT', syscall: 'open', path: 'token' }
Error: ENOENT: no such file or directory, open 'token'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Function.tokenFromFile (/Users/kayce/.nvm/versions/node/v4.4.3/lib/node_modules/polymer-cli/lib/github/github.js:33:19)
    at new Github (/Users/kayce/.nvm/versions/node/v4.4.3/lib/node_modules/polymer-cli/lib/github/github.js:19:50)
    at new GithubGenerator (/Users/kayce/.nvm/versions/node/v4.4.3/lib/node_modules/polymer-cli/lib/init/github.js:21:28)
    at Environment.instantiate (/Users/kayce/.nvm/versions/node/v4.4.3/lib/node_modules/polymer-cli/node_modules/yeoman-environment/lib/environment.js:328:10)
    at Environment.create (/Users/kayce/.nvm/versions/node/v4.4.3/lib/node_modules/polymer-cli/node_modules/yeoman-environment/lib/environment.js:305:15)
    at Environment.run (/Users/kayce/.nvm/versions/node/v4.4.3/lib/node_modules/polymer-cli/node_modules/yeoman-environment/lib/environment.js:364:24)
    at runGenerator (/Users/kayce/.nvm/versions/node/v4.4.3/lib/node_modules/polymer-cli/lib/commands/init.js:60:29)
```

**Comment by justinfagnani** [comment]
Right now you need a github token with repo access stored in a file named `token`. This is temporary.
