### ISSUE TITLE
polymer init fails with third-party generators installed

### ISSUE THREAD

**Issue by ThatJoeMoore** [Polymer/polymer-cli#176]
When a custom init template is installed, `polymer init` fails with the following error:

```
error [TypeError: iterator is not a function]
TypeError: iterator is not a function
    at FindUp._find (/usr/local/lib/node_modules/polymer-cli/node_modules/findup/index.js:60:3)
    at new FindUp (/usr/local/lib/node_modules/polymer-cli/node_modules/findup/index.js:53:8)
    at FindUp (/usr/local/lib/node_modules/polymer-cli/node_modules/findup/index.js:15:12)
    at module.exports (/usr/local/lib/node_modules/polymer-cli/node_modules/findup/index.js:10:10)
    at /usr/local/lib/node_modules/polymer-cli/lib/commands/init.js:94:44
    at Array.map (native)
    at /usr/local/lib/node_modules/polymer-cli/lib/commands/init.js:86:57
    at Environment.resolver.lookup (/usr/local/lib/node_modules/polymer-cli/node_modules/yeoman-environment/lib/resolver.js:50:12)
    at /usr/local/lib/node_modules/polymer-cli/lib/commands/init.js:58:17
    at new Promise (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:193:7)
```

This is due to an issue with the call to findup.

PR is #177.

**Comment by ThatJoeMoore** [comment]
If anybody needs an example third-party template, you can `npm install -g byu-oit-appdev/polymer-yeoman#polymer-cli` for the current yeoman generator that I'm converting to an init template.

**Comment by justinfagnani** [comment]
@ThatJoeMoore just to clarify, does this happen only with generators prefixed with `polymer-init`? If so, it's a bad bug, but maybe slightly less than critical :) I first thought that anyone with other Yeoman generators couldn't use `init`.

**Comment by ThatJoeMoore** [comment]
Yes, it only affects generators prefixed with `polymer init`.  I don't think it's critical, as I doubt many people are writing custom generators yet. I just happened to be putting the finishing touches on one when this was announced and I just had to see if it all worked together (It all works wonderfully, BTW 👏).
