### ISSUE TITLE
Unclear build failure messaging.

### ISSUE THREAD

**Issue by vattay** [Polymer/polymer-cli#179]
### Issue
I was working on the polymer tutorial and found that an incorrect element import on build it fails with a cryptic stack trace, leaving a half generated build directory.

### Reproduce
Run ```polymer init app-drawer-template```
Add iron-ajax ```bower install --save PolymerElements/iron-ajax```
Use on element page, but instead of full path ```<link rel="import" href="../bower_components/iron-ajax/iron-ajax.html">``` use just the directory ```<link rel="import" href="../bower_components/iron-ajax">```
```polymer build```

```
02:42 $ polymer build
info:    Building application...
info:    Generating build/unbundled...
info:    Generating build/bundled...
warn:    Unable to uglify file /Users/avattay/WebstormProjects/v4x-poly/bower_components/marked-element/demo/index.html_script_0.js
warn:    Unable to uglify file /Users/avattay/WebstormProjects/v4x-poly/bower_components/marked-element/test/marked-element.html_script_0.js
warn:    Unable to uglify file /Users/avattay/WebstormProjects/v4x-poly/bower_components/marked-element/test/marked-element.html_script_1.js
warn:    Unable to uglify file /Users/avattay/WebstormProjects/v4x-poly/bower_components/marked-element/test/marked-element.html_script_2.js
warn:    Unable to uglify file /Users/avattay/WebstormProjects/v4x-poly/bower_components/marked-element/test/marked-element.html_script_3.js
warn:    Unable to uglify file /Users/avattay/WebstormProjects/v4x-poly/bower_components/marked-element/test/marked-element.html_script_4.js
warn:    Unable to uglify file /Users/avattay/WebstormProjects/v4x-poly/bower_components/web-component-tester/data/index.html_script_0.js
warn:    Unable to uglify file /Users/avattay/WebstormProjects/v4x-poly/bower_components/web-component-tester/data/index.html_script_2.js
error:   Uncaught exception: TypeError: Cannot read property 'toString' of null
error:   TypeError: Cannot read property 'toString' of null
    at StreamResolver.accept (/Users/avattay/.nvm/versions/node/v4.4.4/lib/node_modules/polymer-cli/lib/build/analyzer.js:196:47)
    at FileLoader.request (/Users/avattay/.nvm/versions/node/v4.4.4/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/loader/file-loader.js:64:27)
    at Analyzer.load (/Users/avattay/.nvm/versions/node/v4.4.4/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:121:32)
    at Analyzer._getDependencies (/Users/avattay/.nvm/versions/node/v4.4.4/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:433:25)
    at Analyzer._dependenciesLoadedFor (/Users/avattay/.nvm/versions/node/v4.4.4/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:401:25)
    at Analyzer._parseHTML (/Users/avattay/.nvm/versions/node/v4.4.4/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:227:50)
    at null._onTimeout (/Users/avattay/.nvm/versions/node/v4.4.4/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by justinfagnani** [comment]
Thanks for the detailed reproduction!
