### ISSUE TITLE
Unknown option throws error

### ISSUE THREAD

**Issue by TimvdLippe** [Polymer/polymer-cli#189]
Invoking `polymer --help` threw the following error:

```
error:   Uncaught exception: UNKNOWN_OPTION: Unknown option: --help
error:   UNKNOWN_OPTION: Unknown option: --help
    at halt (/usr/local/lib/node_modules/polymer-cli/node_modules/command-line-args/lib/argv.js:81:15)
    at Argv.validate (/usr/local/lib/node_modules/polymer-cli/node_modules/command-line-args/lib/argv.js:72:7)
    at CommandLineArgs.parse (/usr/local/lib/node_modules/polymer-cli/node_modules/command-line-args/lib/command-line-args.js:57:10)
    at CommandLineCommands.parse (/usr/local/lib/node_modules/polymer-cli/node_modules/command-line-commands/lib/command-line-commands.js:78:28)
    at PolymerCli.run (/usr/local/lib/node_modules/polymer-cli/lib/polymer-cli.js:122:35)
    at /usr/local/lib/node_modules/polymer-cli/bin/polymer.js:22:7
    at /usr/local/lib/node_modules/polymer-cli/node_modules/resolve/lib/async.js:46:14
    at process (/usr/local/lib/node_modules/polymer-cli/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/local/lib/node_modules/polymer-cli/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/local/lib/node_modules/polymer-cli/node_modules/resolve/lib/async.js:69:43)
```

I expect to either not throw an error and gracefully stop or showing the help as fallback.

**Comment by FredKSchott** [comment]
I'm able to reproduce this as well. 

This is a regression, this case used to be handled.
