### ISSUE TITLE
polymer test command: Cannot find module './build/Release/DTraceProviderBindings'

### ISSUE THREAD

**Issue by guillaumemaka** [Polymer/polymer-cli#196]
Hi,

When i run ```polymer test``` command I got this error:

```
{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/guillaume/.nvm/versions/node/v6.2.0/lib/node_modules/polymer-cli/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/guillaume/.nvm/versions/node/v6.2.0/lib/node_modules/polymer-cli/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/guillaume/.nvm/versions/node/v6.2.0/lib/node_modules/polymer-cli/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3) code: 'MODULE_NOT_FOUND' }
```

Node version : ```v6.2.0```
NPM version : ```v3.9.2```
OS : ```Darwin Kernel Version 15.4.0``` 

Does someone already got this error ?

**Comment by garlicnation** [comment]
@justinfagnani I've been seeing this a lot on my personal machine, but it hasn't caused me any issues.

**Comment by bernardius** [comment]
#https://github.com/chrisa/node-dtrace-provider/issues/71

Looks like "wct-local" is dependent on "launchpad" which is dependent on "restify" which is dependent upon "bunyan" which is dependent upon "dtrace-provider."

**Comment by felixzapata** [comment]
I have the same error.
