### ISSUE TITLE
 Command:polymer build - Tree scoping issue - "Error: Cannot find module gulp"

### ISSUE THREAD

**Issue by thibaultsavary** [Polymer/polymer-cli#198]
Hello,

I got a weird issue trying to launch a build, I don't know if it's related to the way polymer-cli behave but it's the first time I encounter this.

When I executed:
`$ polymer build`

I got this error:
```
C:\Users\xxxxx\Desktop\polymer>polymer build
(node:13876) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
error { Error: Cannot find module 'browser-sync'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\xxxxx\Desktop\gulpfile.js:3:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3) code: 'MODULE_NOT_FOUND' }
Error: Cannot find module 'browser-sync'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\xxxxx\Desktop\gulpfile.js:3:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

As you can see the gulpfile has nothing to do with the project itself, it was on the desktop.

Is this normal or there may be an issue with the tree scoping ? (I don't know if it's the correct terminology, hopefully you'll understand and correct me if it's not)

Edit:

I'm on Win 10 / Node 6.2 / Polymer-cli 0.8.0

**Comment by stmarco** [comment]
Hello 

i have a similar issue, when i do polymer build it gives me:

> error { [Error: Cannot find module 'gulp'] code: 'MODULE_NOT_FOUND' }
>  Error:
> 
>  Cannot find module 'gulp'
>     at Function.Module._resolveFilename (module.js:338:15)
>     at Function.Module._load (module.js:289:25)
>     at Module.require (module.js:366:17)
>     at require (module.js:385:17)
>     at Object.<anonymous> (/Users/mspro/www/gulpfile.js:13:12)
>     at Module._compile (module.js:435:26)
>     at Object.Module._extensions..js (module.js:442:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:313:12)
>     at Module.require (module.js:366:17)
>     at require (module.js:385:17)
> 

gulp is installed globally and i've installed it locally

OSX 10.10.5
gulp version: 3.9.1
bower 1.7.9
npm 3.9.2
node v4.2.4

**Comment by thibaultsavary** [comment]
@stmarco 

It seems that if there a gulpfile.js somehwere higher in the tree it causes that issue.
If you put the folder of your polymer project somewhere where there's no gulpfile.js higher in the tree you won't get the issue. 

For instance in my case, moving the gulpfile.js in a folder on the same tree level solve the issue.

This causes the error
```
C:\Users\xxxxx\Desktop\polymerProject
C:\Users\xxxxx\Desktop\gulpfile.js
```

This doesn't
```
C:\Users\xxxxx\Desktop\polymerProject
C:\Users\xxxxx\Desktop\someFolder\gulpfile.js
```

**Comment by stmarco** [comment]
Thanks Thibault, there was a gulpfile in a directory two levels above my project folder, removing that file solved my issue

**Comment by FredKSchott** [comment]
Glad this worked out! closing this unless there's something easy that we could do to prevent this use case from causing an error.
