### ISSUE TITLE
polymer init - TypeError: this.opts.filename.replace is not a function

### ISSUE THREAD

**Issue by chunkers** [Polymer/polymer-cli#200]
When running `polymer init`, seeing the following error after entering description.

```error:   Uncaught exception: TypeError: this.opts.filename.replace is not a function
error:   TypeError: this.opts.filename.replace is not a function
    at Object.Template.generateSource (/usr/local/lib/node_modules/polymer-cli/node_modules/yeoman-generator/node_modules/mem-fs-editor/node_modules/ejs/lib/ejs.js:528:68)
    at Object.Template.compile (/usr/local/lib/node_modules/polymer-cli/node_modules/yeoman-generator/node_modules/mem-fs-editor/node_modules/ejs/lib/ejs.js:444:12)
    at Object.compile (/usr/local/lib/node_modules/polymer-cli/node_modules/yeoman-generator/node_modules/mem-fs-editor/node_modules/ejs/lib/ejs.js:289:16)
    at handleCache (/usr/local/lib/node_modules/polymer-cli/node_modules/yeoman-generator/node_modules/mem-fs-editor/node_modules/ejs/lib/ejs.js:148:16)
    at Object.exports.render (/usr/local/lib/node_modules/polymer-cli/node_modules/yeoman-generator/node_modules/mem-fs-editor/node_modules/ejs/lib/ejs.js:316:10)
    at copy.process (/usr/local/lib/node_modules/polymer-cli/node_modules/yeoman-generator/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:14:18)
    at applyProcessingFunc (/usr/local/lib/node_modules/polymer-cli/node_modules/yeoman-generator/node_modules/mem-fs-editor/lib/actions/copy.js:13:16)
    at EditionInterface.exports._copySingle (/usr/local/lib/node_modules/polymer-cli/node_modules/yeoman-generator/node_modules/mem-fs-editor/lib/actions/copy.js:51:16)
    at EditionInterface.<anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/yeoman-generator/node_modules/mem-fs-editor/lib/actions/copy.js:38:10)
    at Array.forEach (native)```

**Comment by smartssa** [comment]
More specifically when running `polymer init element` or `polymer init application` - init with the `shop` and the `app-drawer-template` seem to work fine.

**Comment by mgibas** [comment]
Same here

**Comment by kevjs1982** [comment]
Same here on Windows 10 - a console.log of this.opts just before the error line shows

```
{ client: false,
  escapeFunction: { [Function] toString: [Function] },
  compileDebug: true,
  debug: false,
  filename:
   [ 'C:\\Users\\Kev\\AppData\\Roaming\\npm\\node_modules\\polymer-cli\\lib\\init\\element\\templates/**/*',
     'C:\\Users\\Kev\\AppData\\Roaming\\npm\\node_modules\\polymer-cli\\lib\\init\\element\\templates/**/.*',
     '!**/_*' ],
  delimiter: '%',
  strict: false,
  context: undefined,
  cache: false,
  rmWhitespace: undefined,
  localsName: 'locals',
  _with: true }
```

**Comment by chunkers** [comment]
Sorry it is with `polymer init element`
Also running on node version 4.4.5

**Comment by chunkers** [comment]
Closing this issue as its with EJS...thanks for the responses!
https://github.com/mde/ejs/issues/166
