### ISSUE TITLE
polymer init app-drawer-template behind corporate proxy

### ISSUE THREAD

**Issue by hamzaislam** [Polymer/polymer-cli#201]
Tried polymer init app-drawer-template, it couldn't bypass the proxy.  (i do have env variable http_proxy already set to the proxy server without username/pass)

Is there a way to set the proxy directly to polymer config (similar to npm set config proxy?)

```
D:\ProjectGIT\tolweb-mobile-new>polymer init app-drawer-template
info:    Running template app-drawer-template
info:    Downloading latest release of Polymer/app-drawer-template
error:   Could not download release from Polymer/app-drawer-template
error:   Uncaught exception: <HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD>
<BODY>
<FONT face="Helvetica">
<big><strong></strong></big><BR>
</FONT>
<blockquote>
<TABLE border=0 cellPadding=1 width="80%">
<TR><TD>
<FONT face="Helvetica">
<big>Access Denied (authentication_failed)</big>
<BR>
<BR>
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
Your credentials could not be authenticated: "Credentials are missing.". You wil
l not be permitted access until your credentials can be verified.
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
This is typically caused by an incorrect username and/or password, but could als
o be caused by network problems.
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica" SIZE=2>
<BR>
For assistance, contact your network support team.
</FONT>
</TD></TR>
</TABLE>
<FONT face="Helvetica" SIZE=2>
<p>Client URL : https://api.github.com/repos/Polymer/app-drawer-template/release
s</p>
<p>Client IP Address : 10.168.33.210</p>
<p>Client Username : </p>
<p>Date & Time : [25/May/2016:14:41:14 +0800]</p>
<p>Reference Device : n01bcproxy03_NEW</p>
</blockquote>
</FONT>
</BODY></HTML>
```

**Comment by hamzaislam** [comment]
Update: i set the https_proxy variable with my credentials using set https_proxy="http://<domain>%5C<username>:<password>@<hostname>:<port>/" and now encounter the following error (SSL related, so atleast the proxy is being passed through to handshake to the host). 

D:\ProjectGIT\tolweb-mobile-new>polymer init -v app-drawer-template
debug:   got args:
{ args: [ 'init', '-v', 'app-drawer-template' ] }
debug:   adding command build
debug:   adding command help
debug:   adding command init
debug:   adding command lint
debug:   adding command serve
debug:   adding command test
debug:   running...
debug:   command parsed
{ name: 'init',
  options:
   { _all: { verbose: true, name: 'app-drawer-template' },
     global: { verbose: true },
     _none: { name: 'app-drawer-template' } } }
debug:   config read
{ root: 'D:\\ProjectGIT\\tolweb-mobile-new',
  entrypoint: 'D:\\ProjectGIT\\tolweb-mobile-new\\index.html',
  fragments: [],
  inputs: [ 'D:\\ProjectGIT\\tolweb-mobile-new\\index.html' ] }
debug:   Running command...
debug:   creating yeoman environment...
info:    Running template app-drawer-template
debug:   Running generator polymer-init-app-drawer-template:app
info:    Downloading latest release of Polymer/app-drawer-template
error:   Could not download release from Polymer/app-drawer-template
error:   Uncaught exception: certificate has expired
error:   Error: certificate has expired
    at Object.proto.sendError (D:\node\node_modules\polymer-cli\node_modules\git
hub\api\v3.0.0\index.js:30:19)
    at D:\node\node_modules\polymer-cli\node_modules\github\api\v3.0.0\releases.
js:39:29
    at callCallback (D:\node\node_modules\polymer-cli\node_modules\github\index.
js:743:17)
    at ClientRequest.<anonymous> (D:\node\node_modules\polymer-cli\node_modules\
github\index.js:809:17)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:256:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)

**Comment by hamzaislam** [comment]
For now have worked around by cloning the repo and running bower install (for which all proxy config was correctly set).
