### ISSUE TITLE
shared-bundle.html 404s

### ISSUE THREAD

**Issue by robdodson** [Polymer/polymer-cli#226]
Running `polymer build --entrypoint index.html` against the PSK2 branch (https://github.com/PolymerElements/polymer-starter-kit/tree/psk2) generates a file with an import for `shared-bundle.html` but it doesn't actually create a `shared-bundle.html` file so I get a 404.

**Comment by leninmehedy** [comment]
encountered the same issue

**Comment by carofe82** [comment]
I found same issue:
1)

```
$ polymer init application
$ polymer build
$ polymer serve build/bundled
```

2) Open the browser (e.g. Chrome) on http://localhost:8080/

3) Open the Developer Tools and see the GET http://localhost:8080/shared-bundle.html 404 (Not Found)
And the generated index.html has this:

```html
<!DOCTYPE html>
<html>
    <head>
        <link rel="import" href="shared-bundle.html">
        <title>app-test</title>
...
```

**Comment by vuamitom** [comment]
I'm facing the same issue. Any one have a workaround yet?

**Comment by dsnowdon** [comment]
Same problem here

**Comment by stramel** [comment]
Not saying this is a fix but by running, `polymer build --fragment bower_components/polymer/polymer.html` I was able to get past this issue.

**Comment by robdodson** [comment]
yeah i don' think i've seen this issue after creating a proper `polymer.json` that lists a shell and fragments. ex: https://github.com/Polymer/app-drawer-template/blob/master/polymer.json

**Comment by stramel** [comment]
Seems like the `polymer.json` would be the correct route to go. Would it make sense to include a base one in the polymer-cli init?

**Comment by robdodson** [comment]
probably if the templates don't already. But it should also not cause an error if one is missing. I don't *think* it's required but @FredKSchott would know better :)

**Comment by dsnowdon** [comment]
When i build i get this even after adding polymer.html to my polymer.json

{
  "entrypoint": "index.html",
  "shell": "src/forms-app/forms-app.html",
  "fragments": [
    "bower_components/polymer/polymer.html"
  ]
}

|  $ sudo polymer build
info:    Building application...
info:    Generating build/unbundled...
info:    Generating build/bundled...
warn:    Unable to uglify file /Users/Dale/Desktop/Development/test/forms-app/forms-app_test.html_script_0.js
warn:    Unable to uglify file /Users/Dale/Desktop/Development/src/form/behaviors/element-model-generator.html_script_0.js
warn:    Unable to uglify file /Users/Dale/Desktop/Development/bower_components/marked-element/demo/index.html_script_0.js
warn:    Unable to uglify file /Users/Dale/Desktop/Development/bower_components/marked-element/test/marked-element.html_script_0.js
warn:    Unable to uglify file /Users/Dale/Desktop/Development/bower_components/marked-element/test/marked-element.html_script_1.js
warn:    Unable to uglify file /Users/Dale/Desktop/Development/bower_components/marked-element/test/marked-element.html_script_2.js
warn:    Unable to uglify file /Users/Dale/Desktop/Development/bower_components/marked-element/test/marked-element.html_script_3.js
warn:    Unable to uglify file /Users/Dale/Desktop/Development/bower_components/marked-element/test/marked-element.html_script_4.js
warn:    Unable to uglify file /Users/Dale/Desktop/Development/bower_components/web-component-tester/data/index.html_script_0.js
warn:    Unable to uglify file /Users/Dale/Desktop/Development/bower_components/web-component-tester/data/index.html_script_2.js
error:   Promise rejection: Error: no resolver found for ../bower_components/polymer/polymer.html
error:   Error: no resolver found for ../bower_components/polymer/polymer.html
    at FileLoader.request (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Analyzer.load (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:121:32)
    at Analyzer._getDependencies (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:433:25)
    at Analyzer._dependenciesLoadedFor (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:401:25)
    at Analyzer._parseHTML (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:227:50)
    at null._onTimeout (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:92:15)
error:   Promise rejection: Error: no resolver found for ../bower_components/polymer/polymer.html
error:   Error: no resolver found for ../bower_components/polymer/polymer.html
    at FileLoader.request (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Analyzer.load (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:121:32)
    at Analyzer._getDependencies (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:433:25)
    at Analyzer._dependenciesLoadedFor (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:401:25)
    at Analyzer._parseHTML (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:227:50)
    at null._onTimeout (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:92:15)
error:   Promise rejection: Error: no resolver found for ../bower_components/polymer/polymer.html
error:   Error: no resolver found for ../bower_components/polymer/polymer.html
    at FileLoader.request (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Analyzer.load (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:121:32)
    at Analyzer._getDependencies (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:433:25)
    at Analyzer._dependenciesLoadedFor (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:401:25)
    at Analyzer._parseHTML (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:227:50)
    at null._onTimeout (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:92:15)
error:   Promise rejection: Error: no resolver found for ../bower_components/polymer/polymer.html
error:   Error: no resolver found for ../bower_components/polymer/polymer.html
    at FileLoader.request (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Analyzer.load (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:121:32)
    at Analyzer._getDependencies (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:433:25)
    at Analyzer._dependenciesLoadedFor (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:401:25)
    at Analyzer._parseHTML (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:227:50)
    at null._onTimeout (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:92:15)
error:   Promise rejection: Error: no resolver found for ../bower_components/polymer/polymer.html
error:   Error: no resolver found for ../bower_components/polymer/polymer.html
    at FileLoader.request (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Analyzer.load (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:121:32)
    at Analyzer._getDependencies (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:433:25)
    at Analyzer._dependenciesLoadedFor (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:401:25)
    at Analyzer._parseHTML (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:227:50)
    at null._onTimeout (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:92:15)
error:   Promise rejection: Error: no resolver found for ../bower_components/polymer/polymer.html
error:   Error: no resolver found for ../bower_components/polymer/polymer.html
    at FileLoader.request (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Analyzer.load (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:121:32)
    at Analyzer._getDependencies (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:433:25)
    at Analyzer._dependenciesLoadedFor (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:401:25)
    at Analyzer._parseHTML (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:227:50)
    at null._onTimeout (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:92:15)
error:   Promise rejection: Error: no resolver found for ../bower_components/polymer/polymer.html
error:   Error: no resolver found for ../bower_components/polymer/polymer.html
    at FileLoader.request (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Analyzer.load (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:121:32)
    at Analyzer._getDependencies (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:433:25)
    at Analyzer._dependenciesLoadedFor (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:401:25)
    at Analyzer._parseHTML (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:227:50)
    at null._onTimeout (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:92:15)
error:   Promise rejection: Error: no resolver found for ../bower_components/polymer/polymer.html
error:   Error: no resolver found for ../bower_components/polymer/polymer.html
    at FileLoader.request (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Analyzer.load (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:121:32)
    at Analyzer._getDependencies (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:433:25)
    at Analyzer._dependenciesLoadedFor (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:401:25)
    at Analyzer._parseHTML (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:227:50)
    at null._onTimeout (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:92:15)
error:   Promise rejection: Error: no resolver found for ../bower_components/polymer/polymer.html
error:   Error: no resolver found for ../bower_components/polymer/polymer.html
    at FileLoader.request (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Analyzer.load (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:121:32)
    at Analyzer._getDependencies (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:433:25)
    at Analyzer._dependenciesLoadedFor (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:401:25)
    at Analyzer._parseHTML (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:227:50)
    at null._onTimeout (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:92:15)
error:   Promise rejection: Error: no resolver found for ../bower_components/polymer/polymer.html
error:   Error: no resolver found for ../bower_components/polymer/polymer.html
    at FileLoader.request (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Analyzer.load (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:121:32)
    at Analyzer._getDependencies (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:433:25)
    at Analyzer._dependenciesLoadedFor (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:401:25)
    at Analyzer._parseHTML (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:227:50)
    at null._onTimeout (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:92:15)
error:   Promise rejection: Error: no resolver found for ../bower_components/polymer/polymer.html
error:   Error: no resolver found for ../bower_components/polymer/polymer.html
    at FileLoader.request (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Analyzer.load (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:121:32)
    at Analyzer._getDependencies (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:433:25)
    at Analyzer._dependenciesLoadedFor (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:401:25)
    at Analyzer._parseHTML (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:227:50)
    at null._onTimeout (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:92:15)
error:   Promise rejection: Error: no resolver found for ../bower_components/polymer/polymer.html
error:   Error: no resolver found for ../bower_components/polymer/polymer.html
    at FileLoader.request (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Analyzer.load (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:121:32)
    at Analyzer._getDependencies (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:433:25)
    at Analyzer._dependenciesLoadedFor (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:401:25)
    at Analyzer._parseHTML (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:227:50)
    at null._onTimeout (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by robdodson** [comment]
@dsnowdon you wouldn't add `polymer.html` as a fragment. Fragments represent pages in your app. Take a look at https://github.com/Polymer/app-drawer-template for an example

**Comment by stramel** [comment]
@robdodson I was only able to get past issues with the build when i included polymer as well. It was trying to instantiate Polymer multiple times. I tried doing the following:

```
{
  "entrypoint": "index.html",
  "fragments": [
    "src/app/pages/page1.html",
    "src/app/pages/page2.html",
    "src/app/pages/page3.html"
  ]
}
```

The result was Polymer trying to be instantiated multiple times. Adding the `bower_components/polymer/polymer.html` fixed those errors for me.


@dsnowdon Can you post your `polymer-cli`, `node`, and OS versions?

**Comment by FredKSchott** [comment]
hey guys, looking into this now. I can reproduce in both PSK2 and `polymer init application` applications.

**Comment by FredKSchott** [comment]
Still digging...

@dsnowdon based on the output you provided, the CLI cannot find your dependencies. it looks like you still need to run `bower install`. This is a separate issue from the one being reported here.

**Comment by FredKSchott** [comment]
So I can confirm that when a proper polymer.json exists, `build/bundled` is built correctly without any missing `shared-bundle.html` or 404 errors. When polymer CLI doesn't know the app-shell via the `shell` flag/property it attempts to build a more generic `shared-bundle.html` for the application, which is where this bug seems to exist. I'm still digging into why it isn't being created properly.

This explains why:
- You cannot reproduce this bug in PSK2 (has proper polymer.json)
- You can reproduce this bug in application template (no polymer.json)
- You cannot reproduce this bug in application template when you specify a shell via the `--shell` flag

So for now, the work around is to include the `polymer.json` file / `--shell` flag on build.

**Comment by robdodson** [comment]
Thanks for looking into it @FredKSchott 🔍

**Comment by pik** [comment]
What exactly is a 'proper' polymer.json, could we get some more details?

**Comment by FredKSchott** [comment]
@pik check out https://developers.google.com/web/updates/2015/11/app-shell for more info on the app-shell pattern.

and more info on proper polymer.json: https://www.polymer-project.org/1.0/docs/tools/polymer-cli#build
