### ISSUE TITLE
polymer lint fails on basic element project layout

### ISSUE THREAD

**Issue by garcianavalon** [Polymer/polymer-cli#227]
Hi!

I just followed the steps in the [docs](https://www.polymer-project.org/1.0/docs/tools/polymer-cli#element) to create a new element project and when I try to lint the command fails in different ways.

Using the command [specified in the docs
](https://www.polymer-project.org/1.0/docs/tools/polymer-cli#lint)
```
$ polymer lint --input my-el.html
error:   Uncaught exception: UNKNOWN_OPTION: Unknown option: --input
error:   UNKNOWN_OPTION: Unknown option: --input
    at halt (/usr/local/lib/node_modules/polymer-cli/node_modules/command-line-args/lib/argv.js:81:15)
    at Argv.validate (/usr/local/lib/node_modules/polymer-cli/node_modules/command-line-args/lib/argv.js:72:7)
    at CommandLineArgs.parse (/usr/local/lib/node_modules/polymer-cli/node_modules/command-line-args/lib/command-line-args.js:57:10)
    at CommandLineCommands.parse (/usr/local/lib/node_modules/polymer-cli/node_modules/command-line-commands/lib/command-line-commands.js:78:28)
    at PolymerCli.run (/usr/local/lib/node_modules/polymer-cli/lib/polymer-cli.js:115:35)
    at /usr/local/lib/node_modules/polymer-cli/bin/polymer.js:22:7
    at /usr/local/lib/node_modules/polymer-cli/node_modules/resolve/lib/async.js:46:14
    at process (/usr/local/lib/node_modules/polymer-cli/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/local/lib/node_modules/polymer-cli/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/local/lib/node_modules/polymer-cli/node_modules/resolve/lib/async.js:69:43)
garcianavalon at eva in ~/Development/my-el
```

Trying different options based on [the README of this repo](https://github.com/Polymer/polymer-cli#lint)
(I tried creating a polymer.json file with content `{"entrypoint": "my-el.html"}` but the result is the same)
```
$ polymer lint my-el.html
ERROR finding /Users/garcianavalon/Development/my-el/polymer/polymer.html
Error: ENOENT: no such file or directory, open '/Users/garcianavalon/Development/my-el/polymer/polymer.html'
    at Error (native)
```
```
$ polymer lint
ERROR finding /Users/garcianavalon/Development/my-el/polymer/polymer.html
Error: ENOENT: no such file or directory, open '/Users/garcianavalon/Development/my-el/polymer/polymer.html'
    at Error (native)
```

Looks like the import is not working properly
`<link rel="import" href="../polymer/polymer.html">`

I'm using latest version
```
$ polymer --version
0.11.0
```
Any idea on what could be wrong? 
Thanks for any help!
cheers.

**Comment by FredKSchott** [comment]
Hey @garcianavalon, looking into this now

**Comment by 43081j** [comment]
I ran into this recently @FredKSchott, polymer-cli sends the input as `/my-el.html`. If it was `my-el.html`, polylint works fine (well, hydrolysis).

**Comment by FredKSchott** [comment]
@43081j good catch, I was able to trace it there as well. We've done a lot of work with paths for windows, this was probably a casualty of that.

Fix has been submitted here: https://github.com/Polymer/polymer-cli/issues/227

**Comment by garcianavalon** [comment]
@FredKSchott thanks for the quick fix! :)
