### ISSUE TITLE
[FIX] SyntaxError: Unexpected Token <  <Line 1> in index.html

### ISSUE THREAD

**Issue by SayChunKim** [Polymer/polymer-cli#245]
After `polymer init` and `polymer serve`project in CLI, 

`"Uncaught SyntaxError: Unexpected token < "` in first line of index.html

**Recommended fix:**
Add `type="javascript"` under webcomponents-lite.js script tags for resolving the issue

**Comment by FredKSchott** [comment]
Which template are you initializing from? Can you include steps to reproduce from scratch?

**Comment by SayChunKim** [comment]
@FredKSchott thanks for pinpoint. It's from application template

1. `polymer init`
2. select `> application`
3. `polymer build`
4.  `polymer serve` and F12 

Problem reproduced with latest polymer CLI and Ubuntu 14.04

**Comment by justinfagnani** [comment]
I'm unable to reproduce. @SayChunKim do you have any more specifics on your environment?

**Comment by FredKSchott** [comment]
@SayChunKim can you also explain the bug & your fix a bit more? Does this error occur in the CLI, or on the page being served? And including `type="javascript"` on all script tags in the application solves the problem?

**Comment by almielczarek** [comment]
I have encountered the same issue but it found a different fix. The version of polymer I am using is 1.5 and I am on Windows 7.

The "element" template has some issues with the relative links on the imports. If you initialize the template then serve it and go to the demo page in your browser then check the network tab the developer tools in chrome it will show that instead of the webcomponents-lite.js file it is loading your html template file.

If you change the beginning of the hrefs to read "../bower_components/" instead of "../../" then everything loads correctly.

**Comment by justinfagnani** [comment]
Ah... this makes a lot more sense. Thanks for digging into it @almielczarek!

**Comment by justinfagnani** [comment]
@almielczarek I just realized that you are talking about the element template. Right now we don't support  the application workflow with reusable elements. That means two things:

  1. You can't build a reusable element - elements should be built in the context of an app, because we can't know that some dependency that would be bundled with the element isn't also used somewhere else, and we can't have more than one copy of a element/library in an app.
  2. Element projects have to be served from a different URL than application projects because element projects use URLs that reach out of the project folder. That's why `polymer serve` prints this message:

```
Files in this directory are available under the following URLs
    applications: http://localhost:8080
    reusable components: http://localhost:8080/components/p1-element/
```

For elements, you need the second URL.

@SayChunKim I still haven't been able to reproduce this issue with the application template.

**Comment by joaovieira** [comment]
@justinfagnani I just ran into the same issue. `polymer serve` does not work for the element template (does not map /bower_components/) as you're probably aware.

What's the current suggested workflow/process?

I just tried to serve an app from another port and importing from `http://localhost:8080/components/my-el/my-el.html` but it's blocked by CORS. There doesn't seem to be a cors options for the polyserve (pending PolymerLabs/polyserve#45).

**Comment by joaovieira** [comment]
Nevermind.. read your last comment twice and figured it out 😬 

Opening `http://localhost:8080/components/my-el/` and `http://localhost:8080/components/my-el/demo/` work just fine.

**Comment by syu93** [comment]
Hi, I'm using the polymer-cli O.12.0

I encounter the same issue here and something very weird

Using the second URL I'm getting two error.

    Note: for your comprehension, I need to create my element the dist of another project

> webcomponents-lite.js:1 Uncaught SyntaxError: Unexpected token <

And 

> GET http://localhost:8080/var/www/paper-paypal-component/dist/paypal/paypal-element/iron-component-page/iron-component-page.html 404 (Not Found)

Looking at the URL to be sure the path is correct, I saw that I've been redirected to this URL and the path is the full root path of the project.

Hope we can found out a solution, or as it has been said in a previous reply, or I need to drop out the element template project and just create my element ?

**Comment by claudiordgz** [comment]
@justinfagnani I just ran into this issue/design decision about the element builder. Just reiterating... serve elements separately and with the app itself? Do not worry about the paths in the element template? Could we document this somewhere?

**Comment by justinfagnani** [comment]
I'll get some documentation on this in the next release, and hopefully some better output from `polymer serve` and `polymer build` for element-style projects.

**Comment by pik** [comment]
I get this error running `polymer init` and selecting element on cli -v `0.12`

**Comment by larsgk** [comment]
same issue for me - just updated to 0.16 (npm) - will try the 0.17 from github

**Comment by donmccurdy** [comment]
I'm getting a very similar issue, but `polymer serve` works and `polymer build` does not.

Steps to reproduce:

```
polymer init
# → element
# → my-element

polymer serve
# works!

polymer build
# error!
```

Error content:

```
✘  poly-test  polymer build
info:    Building application...
info:    Generating build/unbundled...
info:    Generating build/bundled...
error:   Uncaught exception: Error: file path is not in root: /Users/donmccurdy/Documents/Projects/polymer/polymer.html (/Users/donmccurdy/Documents/Projects/poly-test)
error:   Error: file path is not in root: /Users/donmccurdy/Documents/Projects/polymer/polymer.html (/Users/donmccurdy/Documents/Projects/poly-test)
    at Object.urlFromPath (/Users/donmccurdy/.nvm/versions/node/v4.1.1/lib/node_modules/polymer-cli/node_modules/polymer-build/lib/path-transformers.js:41:15)
    at StreamAnalyzer.getFile (/Users/donmccurdy/.nvm/versions/node/v4.1.1/lib/node_modules/polymer-cli/node_modules/polymer-build/lib/analyzer.js:107:39)
    at StreamResolver.accept (/Users/donmccurdy/.nvm/versions/node/v4.1.1/lib/node_modules/polymer-cli/node_modules/polymer-build/lib/analyzer.js:210:34)
    at FileLoader.request (/Users/donmccurdy/.nvm/versions/node/v4.1.1/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/loader/file-loader.js:64:27)
    at Analyzer.load (/Users/donmccurdy/.nvm/versions/node/v4.1.1/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:121:32)
    at Analyzer._getDependencies (/Users/donmccurdy/.nvm/versions/node/v4.1.1/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:433:25)
    at Analyzer._dependenciesLoadedFor (/Users/donmccurdy/.nvm/versions/node/v4.1.1/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:401:25)
    at Analyzer._parseHTML (/Users/donmccurdy/.nvm/versions/node/v4.1.1/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:227:50)
    at null._onTimeout (/Users/donmccurdy/.nvm/versions/node/v4.1.1/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:89:15)
```

It looks like relative paths are correct for local development, but not for building the code? I'm using Polymer CLI v0.16.0.

**Comment by PatelJay017** [comment]
Error:(10, 0) Project with path 'com.facebook.yogajni' could not be found in root project 'litho-master'.
<a href="openFile:/home/rgi-4/Desktop/JAY/Demo/A_Matirial_Desion_Demo/litho-master/build.gradle">Open File</a> 

Please Help Me for Above Error

**Comment by achuthhadnoor** [comment]
on polymer serve i am getting the link below 
http://127.0.0.1:8080 
but i want the url as http://localhost:8080
how can i change it?

**Comment by xelra** [comment]
I just installed some updates. Unfortunately I can't exactly recall which and suddenly I couldn't serve my app anymore.
I get `Uncaught SyntaxError: Invalid or unexpected token` from `webcomponents-loader.js`.

I then created a completely new project polymer-starter-kit application and it has the same error.
