### ISSUE TITLE
build error: Cannot find module 'sw-toolbox/sw-toolbox.js'

### ISSUE THREAD

**Issue by SPAHI4** [Polymer/polymer-cli#250]
```
error:   Promise rejection: Error: Cannot find module 'sw-toolbox/sw-toolbox.js'
error:   Error: Cannot find module 'sw-toolbox/sw-toolbox.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.require.resolve (internal/module.js:23:19)
    at /home/spahi4/n/lib/node_modules/polymer-cli/node_modules/sw-precache/lib/sw-precache.js:184:37
    at new Promise (/home/spahi4/n/lib/node_modules/polymer-cli/node_modules/core-js/modules/es6.promise.js:193:7)
    at generate (/home/spahi4/n/lib/node_modules/polymer-cli/node_modules/sw-precache/lib/sw-precache.js:78:10)
    at /home/spahi4/n/lib/node_modules/polymer-cli/node_modules/sw-precache/lib/sw-precache.js:295:5
    at new Promise (/home/spahi4/n/lib/node_modules/polymer-cli/node_modules/core-js/modules/es6.promise.js:193:7)
    at Object.write (/home/spahi4/n/lib/node_modules/polymer-cli/node_modules/sw-precache/lib/sw-precache.js:275:10)
    at writeSWPrecache (/home/spahi4/n/lib/node_modules/polymer-cli/lib/build/sw-precache.js:20:23)
    at Object.generateServiceWorker (/home/spahi4/n/lib/node_modules/polymer-cli/lib/build/sw-precache.js:47:12)

```

**Comment by SPAHI4** [comment]
I have installed sw-toolbox package in bower and as global in npm but nothing changes

**Comment by justinfagnani** [comment]
Seems like the npm install might have failed. sw-toolbox does not need to be a global install.

**Comment by addyosmani** [comment]
The last release of toolbox changed the path for this dep. We have an open bug to restore it to what it was before. I'd hold off a day or two and this should be resolved.

**Comment by justinfagnani** [comment]
Ok, we're blocked on https://github.com/GoogleChrome/sw-toolbox/issues/143 then

**Comment by justinfagnani** [comment]
@addyosmani holding off a day means that new installs of CLI are broken during the next day. I suppose we should hard-code a version?

**Comment by justinfagnani** [comment]
This should be fixed upstream now: https://github.com/GoogleChrome/sw-toolbox/issues/143#event-687152248

@SPAHI4 can you try a fresh install?

**Comment by SPAHI4** [comment]
@justinfagnani works fine 👍🏼

**Comment by innomon** [comment]
Thanks ! worked for me too  :+1:
