### ISSUE TITLE
Add support for symlinks

### ISSUE THREAD

**Issue by JosefJezek** [Polymer/polymer-cli#263]
Could you add support for symlinks? I have created symlink `src/app-themes/current-theme` to `src/app-themes/default-theme` on Linux. I get error by running `polymer build`...

```
error:   Promise rejection: Error: no resolver found for src/app-themes/current-theme/global-styles/global-styles.html
error:   Error: no resolver found for src/app-themes/current-theme/global-styles/global-styles.html
    at FileLoader.request (/usr/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Analyzer.load (/usr/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:121:32)
    at Analyzer._getDependencies (/usr/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:433:25)
    at Analyzer._dependenciesLoadedFor (/usr/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:401:25)
    at Analyzer._parseHTML (/usr/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:227:50)
    at Timeout._onTimeout (/usr/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

I need for PWA template https://github.com/StartPolymer/progressive-web-app-template

**Comment by JosefJezek** [comment]
Resolved. Working in v1. Thank you.
