### ISSUE TITLE
Issue with gulp-htmlmin when running polymer build 

### ISSUE THREAD

**Issue by maisnamraju** [Polymer/polymer-cli#308]
I am not sure if this is an issue with the gulp plugin or the polymer tool but I have reinstalled all the concerned packages and can't seem to get rid of the error. 

```
warn:    Unable to uglify file /home/kseguy/Desktop/bluewater_polymer_new/client/src/behaviors/crews-table-behavior.html_script_0.js
warn:    Unable to uglify file /home/kseguy/Desktop/bluewater_polymer_new/client/src/pages/account/account.html_script_0.js
warn:    Unable to uglify file /home/kseguy/Desktop/bluewater_polymer_new/client/src/pages/boats/boat-check-dialog.html_script_0.js
warn:    Unable to uglify file /home/kseguy/Desktop/bluewater_polymer_new/client/src/pages/boats/boat-crew-list.html_script_0.js
warn:    Unable to uglify file /home/kseguy/Desktop/bluewater_polymer_new/client/src/pages/boats/boat-form.html_script_0.js
warn:    Unable to uglify file /home/kseguy/Desktop/bluewater_polymer_new/client/src/pages/boats/boat-handicaps-form.html_script_0.js
warn:    Unable to uglify file /home/kseguy/Desktop/bluewater_polymer_new/client/src/pages/boats/boat-handicaps-table.html_script_0.js
warn:    Unable to uglify file /home/kseguy/Desktop/bluewater_polymer_new/client/src/pages/boats/boat-list.html_script_0.js
warn:    Unable to uglify file /home/kseguy/Desktop/bluewater_polymer_new/client/src/pages/boats/boat-tracker-list.html_script_0.js
warn:    Unable to uglify file /home/kseguy/Desktop/bluewater_polymer_new/client/src/pages/boats/boats.html_script_0.js
warn:    Unable to uglify file /home/kseguy/Desktop/bluewater_polymer_new/client/src/pages/crews/crew-check-form.html_script_0.js
warn:    Unable to uglify file /home/kseguy/Desktop/bluewater_polymer_new/client/src/pages/crews/crew-email-validate.html_script_0.js
warn:    Unable to uglify file /home/kseguy/Desktop/bluewater_polymer_new/client/src/pages/crews/crew-form.html_script_0.js
warn:    Unable to uglify file /home/kseguy/Desktop/bluewater_polymer_new/client/src/pages/crews/crew-table.html_script_0.js
warn:    Unable to uglify file /home/kseguy/Desktop/bluewater_polymer_new/client/src/pages/crews/crews.html_script_0.js
warn:    Unable to uglify file /home/kseguy/Desktop/bluewater_polymer_new/client/src/pages/handicaps/handicaps.html_script_0.js
warn:    Unable to uglify file /home/kseguy/Desktop/bluewater_polymer_new/client/src/pages/signin/signin.html_script_0.js
warn:    Unable to uglify file /home/kseguy/Desktop/bluewater_polymer_new/client/src/pages/signup/signup.html_script_0.js
warn:    Unable to uglify file /home/kseguy/Desktop/bluewater_polymer_new/client/src/pages/trackers/trackers.html_script_0.js
warn:    Unable to uglify file /home/kseguy/Desktop/bluewater_polymer_new/client/bower_components/paper-datatable/paper-datatable-card.html_script_0.js
warn:    Unable to uglify file /home/kseguy/Desktop/bluewater_polymer_new/client/bower_components/paper-datatable/paper-datatable.html_script_0.js
warn:    Unable to uglify file /home/kseguy/Desktop/bluewater_polymer_new/client/bower_components/marked-element/demo/index.html_script_0.js
warn:    Unable to uglify file /home/kseguy/Desktop/bluewater_polymer_new/client/bower_components/marked-element/test/marked-element.html_script_0.js
warn:    Unable to uglify file /home/kseguy/Desktop/bluewater_polymer_new/client/bower_components/marked-element/test/marked-element.html_script_1.js
warn:    Unable to uglify file /home/kseguy/Desktop/bluewater_polymer_new/client/bower_components/marked-element/test/marked-element.html_script_2.js
warn:    Unable to uglify file /home/kseguy/Desktop/bluewater_polymer_new/client/bower_components/marked-element/test/marked-element.html_script_3.js
warn:    Unable to uglify file /home/kseguy/Desktop/bluewater_polymer_new/client/bower_components/marked-element/test/marked-element.html_script_4.js
warn:    Unable to uglify file /home/kseguy/Desktop/bluewater_polymer_new/client/bower_components/paper-datatable/docs/docs.html_script_0.js
error:   Uncaught exception: Error in plugin 'gulp-htmlmin'
Parse Error: <line x1="4" y1="20" x2="200" y2="200" style="stroke:red;stroke-width:10px;stroke-dasharray: 10px, 4px;stroke-linecap: " butt"="" id="line1"></line>
        <line x1="100" y1="40" x2="250" y2="250" style="stroke:green;stroke-width:5px;stroke-dasharray: 5px,3px,2px;stroke-linecap: " round"="" id="line2"></line>
        <line x1="50" y1="100" x2="200" y2="200" style="stroke:blue;stroke-width:9px;stroke-dasharray: 1px;stroke-linecap: " square"="" id="line3"></line>
        <line x1="4" y1="200" x2="200" y2="200" style="stroke:black;stroke-width:20px;stroke-dasharray: 1px,2px,3px,4px,5px;stroke-linecap: " butt"="" id="line4"></line>
        <line x1="8" y1="275" x2="100" y2="444" style="stroke:orange;stroke-width:11px;stroke-dasharray: 1px;stroke-linecap: " round"="" id="line5"></line>
        <line x1="20" y1="344" x2="50" y2="400" style="stroke:yellow;stroke-width:30px;stroke-dasharray: 5px;stroke-linecap: " square"="" id="line6"></line>
        <line x1="4" y1="400" x2="450" y2="450" style="stroke:purple;stroke-width:1px;stroke-dasharray: 11px, 4px;stroke-linecap: " butt"="" id="line7"></line>
    </svg>
    <canvas id="canvas" width="500" height="500"></canvas>


</body></html>
error:   Error: Parse Error: <line x1="4" y1="20" x2="200" y2="200" style="stroke:red;stroke-width:10px;stroke-dasharray: 10px, 4px;stroke-linecap: " butt"="" id="line1"></line>
        <line x1="100" y1="40" x2="250" y2="250" style="stroke:green;stroke-width:5px;stroke-dasharray: 5px,3px,2px;stroke-linecap: " round"="" id="line2"></line>
        <line x1="50" y1="100" x2="200" y2="200" style="stroke:blue;stroke-width:9px;stroke-dasharray: 1px;stroke-linecap: " square"="" id="line3"></line>
        <line x1="4" y1="200" x2="200" y2="200" style="stroke:black;stroke-width:20px;stroke-dasharray: 1px,2px,3px,4px,5px;stroke-linecap: " butt"="" id="line4"></line>
        <line x1="8" y1="275" x2="100" y2="444" style="stroke:orange;stroke-width:11px;stroke-dasharray: 1px;stroke-linecap: " round"="" id="line5"></line>
        <line x1="20" y1="344" x2="50" y2="400" style="stroke:yellow;stroke-width:30px;stroke-dasharray: 5px;stroke-linecap: " square"="" id="line6"></line>
        <line x1="4" y1="400" x2="450" y2="450" style="stroke:purple;stroke-width:1px;stroke-dasharray: 11px, 4px;stroke-linecap: " butt"="" id="line7"></line>
    </svg>
    <canvas id="canvas" width="500" height="500"></canvas>


</body></html>
    at new HTMLParser (/home/kseguy/.npm-global/lib/node_modules/polymer-cli/node_modules/html-minifier/src/htmlparser.js:236:13)
    at minify (/home/kseguy/.npm-global/lib/node_modules/polymer-cli/node_modules/html-minifier/src/htmlminifier.js:861:3)
    at Object.exports.minify (/home/kseguy/.npm-global/lib/node_modules/polymer-cli/node_modules/html-minifier/src/htmlminifier.js:1216:10)
    at /home/kseguy/.npm-global/lib/node_modules/polymer-cli/node_modules/gulp-html-minifier/index.js:51:40
    at wrappedMapper (/home/kseguy/.npm-global/lib/node_modules/polymer-cli/node_modules/map-stream/index.js:84:19)
    at Stream.stream.write (/home/kseguy/.npm-global/lib/node_modules/polymer-cli/node_modules/map-stream/index.js:96:21)
    at Readable.ondata (_stream_readable.js:556:20)
    at emitOne (events.js:96:13)
    at Readable.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
```

**Comment by jfletcher-nuxeo** [comment]
Most likely an error in your source. For example look at `round"=""`. I saw the same error when one of our attributes was missing an `=`. I think uglify tried to add an `=` but can't quite fix the bad source :)

**Comment by FredKSchott** [comment]
Please run the same command with the `--verbose` flag to see what exactly caused the uglify error in each file. Feel free to re-open if the error it gives isn't in your source code.

**Comment by maisnamraju** [comment]
The issue was with one of the libraries. Thanks

**Comment by FredKSchott** [comment]
👍 glad it worked, the next version of polymer-cli will turn these errors into warnings so so it shouldn't be an issue.

**Comment by Shah-Parth** [comment]
@maisnamraju what did you have to do to fix this issue?

**Comment by maisnamraju** [comment]
@Shah-Parth I went to the source and rewrote the part that were causing the issue.
