### ISSUE TITLE
build fails noisily when run on an element project

### ISSUE THREAD

**Issue by FredKSchott** [Polymer/polymer-cli#338]
#### Steps to Reproduce
1. polymer init element
2. polymer build

#### Expected Results
Some error explaining that elements cannot be built.

#### Actual Results
```
error:   Promise rejection: Error: no resolver found for ../polymer/polymer.html
error:   Error: no resolver found for ../polymer/polymer.html
at FileLoader.request (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
at Analyzer.load (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:121:32)
at Analyzer._getDependencies (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:433:25)
at Analyzer._dependenciesLoadedFor (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:401:25)
at Analyzer._parseHTML (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:227:50)
at null._onTimeout (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:125:39)
at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by rof20004** [comment]
In my case, the problem was:

let app = document.querySelector('#app');

polymer build not recognize 'let' like a variable declaration.
