### ISSUE TITLE
Polymer binary is failing to init/serve

### ISSUE THREAD

**Issue by zigmoid** [Polymer/polymer-cli#339]
### Description

Polymer binary is failing to init/serve

### Versions & Environment

- Polymer CLI: Unable to find
- node: v0.10.25
- Operating System: Ubuntu 14.04 trusty(x86-64)

#### Steps to Reproduce

1. $ sudo npm install -g polymer-cli
2. $ sudo polymer serve OR $ polymer serve

#### Actual Results

$ /usr/local/lib/node_modules/polymer-cli/bin/polymer.js:16
const resolve = require('resolve');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by FredKSchott** [comment]
See https://github.com/Polymer/polymer-cli#supported-nodejs-versions, we don't currently support v0.10.25
