### ISSUE TITLE
Installing latest polymer cli error

### ISSUE THREAD

**Issue by gusdecool** [Polymer/polymer-cli#355]
tested using npm@v2.15.1 and OSXv10.11.6

```
$ sudo npm install -g polymer-cli
Password:
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN optional dep failed, continuing wct-local@2.0.11
 
> spawn-sync@1.0.15 postinstall /usr/local/lib/node_modules/polymer-cli/node_modules/inquirer/node_modules/external-editor/node_modules/spawn-sync
> node postinstall

npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
 
> sauce-connect-launcher@0.14.0 postinstall /usr/local/lib/node_modules/polymer-cli/node_modules/web-component-tester/node_modules/wct-sauce/node_modules/sauce-connect-launcher
> node scripts/install.js

npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
 
> wct-sauce@1.8.4 postinstall /usr/local/lib/node_modules/polymer-cli/node_modules/web-component-tester/node_modules/wct-sauce
> node scripts/postinstall.js

Prefetching the Sauce Connect binary.
Missing Sauce Connect local proxy, downloading dependency
This will only happen once.
Downloading 2.95MB
Unzipping sc-4.3.13-osx.zip
Removing sc-4.3.13-osx.zip
Sauce Connect downloaded correctly
Removing /usr/local/lib/node_modules/polymer-cli/node_modules/web-component-tester/node_modules/wct-sauce/node_modules/sauce-connect-launcher/sc/sc-4.3.13-osx.zip
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "polymer-cli"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1

npm ERR! Invalid name: "@types/clone"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gusdecool/npm-debug.log
```

**Comment by gusdecool** [comment]
after update to Node@v6.3.1 and NPM@3.10.3, installation working fine.
Probably we need to put information what is the minimum requirement in documentation

**Comment by dwelby101** [comment]
After updating node to the same versions you mentioned above I am still having trouble installing polymer-cli.

I see the errors below

```
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/usr/local/bin/polymer -> /usr/local/lib/node_modules/polymer-cli/bin/polymer.js

> dtrace-provider@0.6.0 install /usr/local/lib/node_modules/polymer-cli/node_modules/dtrace-provider
> node scripts/install.js

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
path.js:1144
          cwd = process.cwd();
                        ^

Error: EACCES: permission denied, uv_cwd
    at Error (native)
    at Object.resolve (path.js:1144:25)
    at startup (bootstrap_node.js:122:32)
    at bootstrap_node.js:467:3
npm WARN install:dtrace-provider@0.6.0 dtrace-provider@0.6.0 install: `node scripts/install.js`
npm WARN install:dtrace-provider@0.6.0 Exit status 1

> spawn-sync@1.0.15 postinstall /usr/local/lib/node_modules/polymer-cli/node_modules/spawn-sync
> node postinstall

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
path.js:1144
          cwd = process.cwd();
                        ^

Error: EACCES: permission denied, uv_cwd
    at Error (native)
    at Object.resolve (path.js:1144:25)
    at startup (bootstrap_node.js:122:32)
    at bootstrap_node.js:467:3
/usr/local/lib
└── (empty)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "polymer-cli"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the spawn-sync@1.0.15 postinstall script 'node postinstall'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs spawn-sync
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/davidwelby/Desktop/test/npm-debug.log
npm ERR! code 1
```

**Comment by FredKSchott** [comment]
@gusdecool thanks for reporting! Can you confirm your npm version by running `npm --version`? Scoped packages like "@types/clone" are supported in the version of npm that ships with Node v4 LTS (npm v2.15.8) so i'm confused why it would be complaining.

@dwelby101 it looks like you have a permissions issue with your npm directory, I'd suggest googling the error message ("shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied") and poking around. Unfortunately this isn't a CLI issue.

**Comment by dwelby101** [comment]
Cheers @FredKSchott, seems you were right, apparently it is an intermittent issue some packages suffer (related to node or npm, not exactly sure) according to[ this ](https://github.com/ContentMine/quickscrape/issues/1#issuecomment-44762588) but the command `sudo npm install --unsafe-perm -g polymer-cli` worked a treat. Thanks 👍

**Comment by graynun** [comment]
Hi! I just ended up facing a similar problem with this!

> $ sudo npm install --unsafe-perm -g polymer-cli
> npm ERR! Darwin 15.6.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--unsafe-perm" "-g" "polymer-cli"
> npm ERR! node v6.4.0
> npm ERR! npm  v3.10.3
> 
> npm ERR! Invalid name: "@types/node"
> npm ERR! 
> npm ERR! If you need help, you may report this error at:
> npm ERR!     <https://github.com/npm/npm/issues>
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /usr/local/bin/npm-debug.log

my node version is 6.4.0 and npm 3.10.3, as mentioned above.
Have any idea why `npm ERR! Invalid name: "@types/node"` happens?

**Comment by FredKSchott** [comment]
@graynorton Woo! Thanks for updating the issue with your fix.

**Comment by hkirk** [comment]
With latest version I get this error

`$ sudo npm install -g polymer-cli
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "polymer-cli"
npm ERR! node v7.7.3
npm ERR! npm  v4.1.2

npm ERR! Invalid name: "@types/chalk"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/henrik/Private/pwa-from-scratch-master/npm-debug.log`

**Comment by opentaps** [comment]
I think the problem is your npm and node versions are not compatible.  I got this error with
$ sudo npm i -g polymer-cli
Password:
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-g" "polymer-cli"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10

npm ERR! Invalid name: "@types/chalk"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

But then I updated my npm:
$ sudo /usr/local/bin/npm i -g nam

With npm 4.5.0 and node 6.10.13 polymer-cli was able to install.

**Comment by willinspire** [comment]
### Checking Versions
I verified the versions of both npm and node as follows:
```
$ npm --version
5.3.0
$ node --version
v8.1.4
```

### Attempting Install
I used the suggested additional command parameter "--unsafe-perm" (suggested by @dwelby101 above) during this installation attempt and was unsuccessful. See terminal readout below:
```
$ sudo npm install --unsafe-perm -g polymer-cli
[sudo] password for h8rt3rmin8r: 
npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path, but please help to create it: https://github.com/bower/bower/issues/2467
npm WARN deprecated @types/assert@0.0.29: See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/12826
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/polymerelements/test-fixture.git /home/h8rt3rmin8r/.npm/_cacache/tmp/git-clone-d96d2838
npm ERR! /home/h8rt3rmin8r/.npm/_cacache/tmp/git-clone-d96d2838/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/h8rt3rmin8r/.npm/_logs/2017-07-17T10_57_30_817Z-debug.log
```
