### ISSUE TITLE
Redirect support in polymer build

### ISSUE THREAD

**Issue by mgiuffrida** [Polymer/polymer-cli#368]
Apps whose URL structures don't map one-to-one with the file system need vulcanize-style `--redirect` support to use `polymer build`.

How difficult would it be to pass these arguments to `polymer build` for bundling and vulcanizing? ( @garlicnation We've talked about this before, let's just get some options down.)

Example where Chrome WebUI wants to vulcanize Downloads:

[entrypoint](https://cs.chromium.org/chromium/src/chrome/browser/resources/md_downloads/downloads.html?sq=package:chromium&dr)

[script we use to vulcanize](https://cs.chromium.org/chromium/src/chrome/browser/resources/md_downloads/vulcanize.py?sq=package:chromium&dr)

polymer build command and error output since we can't use resolvers:

```
~/src/chrome/browser/resources/md_downloads % polymer build --entrypoint downloads.html --shell manager.html
info:    Building application...
info:    Generating build/unbundled...
info:    Generating build/bundled...
error:   Promise rejection: Error: no resolver found for chrome://downloads/shared_style.css
error:   Error: no resolver found for chrome://downloads/shared_style.css
    at FileLoader.request (/usr/local/google/home/michaelpg/.nvm/versions/node/v5.7.0/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Analyzer._parseHTML (/usr/local/google/home/michaelpg/.nvm/versions/node/v5.7.0/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:257:61)
    at null._onTimeout (/usr/local/google/home/michaelpg/.nvm/versions/node/v5.7.0/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:92:15)
error:   Promise rejection: Error: no resolver found for chrome://downloads/manager.js
error:   Error: no resolver found for chrome://downloads/manager.js
    at FileLoader.request (/usr/local/google/home/michaelpg/.nvm/versions/node/v5.7.0/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Analyzer._processScript (/usr/local/google/home/michaelpg/.nvm/versions/node/v5.7.0/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:378:36)
    at /usr/local/google/home/michaelpg/.nvm/versions/node/v5.7.0/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:301:44
    at Array.forEach (native)
    at Analyzer._processScripts (/usr/local/google/home/michaelpg/.nvm/versions/node/v5.7.0/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:300:21)
    at Analyzer._parseHTML (/usr/local/google/home/michaelpg/.nvm/versions/node/v5.7.0/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:161:39)
    at null._onTimeout (/usr/local/google/home/michaelpg/.nvm/versions/node/v5.7.0/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:92:15)
error:   Promise rejection: Error: no resolver found for chrome://downloads/manager.js
error:   Error: no resolver found for chrome://downloads/manager.js
    at FileLoader.request (/usr/local/google/home/michaelpg/.nvm/versions/node/v5.7.0/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Analyzer._processScript (/usr/local/google/home/michaelpg/.nvm/versions/node/v5.7.0/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:378:36)
    at /usr/local/google/home/michaelpg/.nvm/versions/node/v5.7.0/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:301:44
    at Array.forEach (native)
    at Analyzer._processScripts (/usr/local/google/home/michaelpg/.nvm/versions/node/v5.7.0/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:300:21)
    at Analyzer._parseHTML (/usr/local/google/home/michaelpg/.nvm/versions/node/v5.7.0/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:161:39)
    at null._onTimeout (/usr/local/google/home/michaelpg/.nvm/versions/node/v5.7.0/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:92:15)
error:   Promise rejection: Error: no resolver found for chrome://downloads/manager.js
error:   Error: no resolver found for chrome://downloads/manager.js
    at FileLoader.request (/usr/local/google/home/michaelpg/.nvm/versions/node/v5.7.0/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Analyzer._processScript (/usr/local/google/home/michaelpg/.nvm/versions/node/v5.7.0/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:378:36)
    at /usr/local/google/home/michaelpg/.nvm/versions/node/v5.7.0/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:301:44
    at Array.forEach (native)
    at Analyzer._processScripts (/usr/local/google/home/michaelpg/.nvm/versions/node/v5.7.0/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:300:21)
    at Analyzer._parseHTML (/usr/local/google/home/michaelpg/.nvm/versions/node/v5.7.0/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:161:39)
    at null._onTimeout (/usr/local/google/home/michaelpg/.nvm/versions/node/v5.7.0/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:92:15)

```

**Comment by FredKSchott** [comment]
Can you confirm you're using the latest version of the CLI, v0.14.0? We just started ignoring external resources, so I'd love to confirm that we're not still seeing errors there.

This is all technically still possible in the same way it is today in Vulcanize, but we're currently re-writing our analyzer which is where this redirect-resolution would occur. Our current plans is to move polymer-cli/polymer-build over to analyzer 2.0 asap, and then we could tackle this.

We'll want to think about where this configuration should live, since a project relies on it for build I could see it fitting as a valid field in your `polymer.json`.

**Comment by mgiuffrida** [comment]
That was 0.13.0. FWIW, the error is different now in 0.14.0:

```
~/src/chrome/browser/resources/md_downloads % polymer build --entrypoint downloads.html --shell manager.html
info:    Building application...
info:    Generating build/unbundled...
info:    Generating build/bundled...
error:   Uncaught exception: Error: ENOENT: no such file or directory, open '/usr/local/home/src/chrome/browser/resources/md_downloads/chrome:/resources/html/cr.html'
error:   Error: ENOENT: no such file or directory, open '/usr/local/home/src/chrome/browser/resources/md_downloads/chrome:/resources/html/cr.html'
    at Error (native)
```

**Comment by FredKSchott** [comment]
For anyone following along at home... I'm looking into this now :)
