### ISSUE TITLE
issue to install polymer-cli by npm install from git pull git-github-com-polymerelements-test-fixture

### ISSUE THREAD

**Issue by JennyLiu** [Polymer/polymer-cli#370]
Run:
npm install -g polymer-cli

Got the below error. I am behind firewall, got the proxy setting right, OK with other NPM install.
error:
```
D:\Projects\community\community-exchange>npm install -g polymer-cli
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> spawn-sync@1.0.15 postinstall D:\MyProgramFile\nodejs\node_modules\polymer-cli\node_modules\inquirer\node_modules\external-editor\node_mod
ules\spawn-sync
> node postinstall

npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0
 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm ERR! addLocal Could not install C:\Users\204058~1\AppData\Local\Temp\npm-11444-8049d67c\git-cache-55e9cbad832c\05514d6f32ade6fe54de5b242
bbb43ea9dcff3c0
npm ERR! addLocal Could not install C:\Users\204058~1\AppData\Local\Temp\npm-11444-8049d67c\git-cache-920c78968079\05514d6f32ade6fe54de5b242
bbb43ea9dcff3c0
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:829:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:319:11)
npm WARN addRemoteGit     at emitOne (events.js:77:13)
npm WARN addRemoteGit     at Socket.emit (events.js:169:7)
npm WARN addRemoteGit     at Pipe._onclose (net.js:486:12)
npm WARN addRemoteGit  polymerelements/test-fixture resetting remote C:\Users\204058054\AppData\Roaming\npm-cache\_git-remotes\git-github-co
m-polymerelements-test-fixture-git-b6f9dabf because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origi
n.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\204058054\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:polymerelements/t
est-fixture.git C:\Users\204058054\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-b6f9dabf: Cloning
into bare repository 'C:\Users\204058054\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-b6f9dabf'...

npm ERR! git clone --template=C:\Users\204058054\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:polymerelements/t
est-fixture.git C:\Users\204058054\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-b6f9dabf: Host key
 verification failed.
npm ERR! git clone --template=C:\Users\204058054\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:polymerelements/t
est-fixture.git C:\Users\204058054\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-b6f9dabf: fatal: C
ould not read from remote repository.
npm ERR! git clone --template=C:\Users\204058054\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:polymerelements/t
est-fixture.git C:\Users\204058054\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-b6f9dabf:
npm ERR! git clone --template=C:\Users\204058054\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:polymerelements/t
est-fixture.git C:\Users\204058054\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-b6f9dabf: Please m
ake sure you have the correct access rights
npm ERR! git clone --template=C:\Users\204058054\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:polymerelements/t
est-fixture.git C:\Users\204058054\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-b6f9dabf: and the
repository exists.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\MyProgramFile\\nodejs\\node.exe" "C:\\Users\\204058054\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "insta
ll" "-g" "polymer-cli"
npm ERR! node v4.5.0
npm ERR! npm  v2.13.1
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\204058054\AppData\Roaming\npm-cache\_git-remotes\_templates --
mirror git@github.com:polymerelements/test-fixture.git C:\Users\204058054\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymereleme
nts-test-fixture-git-b6f9dabf
npm ERR! Cloning into bare repository 'C:\Users\204058054\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture
-git-b6f9dabf'...
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Projects\community\community-exchange\npm-debug.log
```

**Comment by FredKSchott** [comment]
This is an npm issue, please see https://github.com/npm/npm/issues/9401 or https://www.google.com/search#q=npm%20install%20proxy%20github for help connecting to github /w proxy setting.

**Comment by gifthlong** [comment]
Hi all this is still failing for me. Please see config:

```
26664 info git [ 'clone',
26664 info git   '--template=C:\\Users\\ghlongoane\\AppData\\Roaming\\npm-cache\\_git-remotes\\_templates',
26664 info git   '--mirror',
26664 info git   'git://github.com/polymerelements/test-fixture.git',
26664 info git   'C:\\Users\\ghlongoane\\AppData\\Roaming\\npm-cache\\_git-remotes\\git-github-com-polymerelements-test-fixture-git-4485c51b' ]
26665 error git clone --template=C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/polymerelements/test-fixture.git C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-4485c51b: Cloning into bare repository 'C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-4485c51b'...
26665 error git clone --template=C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/polymerelements/test-fixture.git C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-4485c51b: fatal: unable to access 'https://github.com/polymerelements/test-fixture.git/': Failed to connect to github.com port 443: Timed out
26666 silly tryHTTPS attempting to clone git+https://github.com/polymerelements/test-fixture.git
26667 silly tryClone cloning polymerelements/test-fixture via git+https://github.com/polymerelements/test-fixture.git
26668 verbose tryClone git-https-github-com-polymerelements-test-fixture-git-a8830b55 not in flight; caching
26669 verbose correctMkdir C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes correctMkdir not in flight; initializing
26670 info git [ 'config', '--get', 'remote.origin.url' ]
26671 warn addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
26671 warn addRemoteGit
26671 warn addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
26671 warn addRemoteGit     at emitTwo (events.js:106:13)
26671 warn addRemoteGit     at ChildProcess.emit (events.js:191:7)
26671 warn addRemoteGit     at maybeClose (internal/child_process.js:877:16)
26671 warn addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
26671 warn addRemoteGit  polymerelements/test-fixture resetting remote C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-polymerelements-test-fixture-git-a8830b55 because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
26671 warn addRemoteGit
26671 warn addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
26671 warn addRemoteGit     at emitTwo (events.js:106:13)
26671 warn addRemoteGit     at ChildProcess.emit (events.js:191:7)
26671 warn addRemoteGit     at maybeClose (internal/child_process.js:877:16)
26671 warn addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
26671 warn addRemoteGit   killed: false,
26671 warn addRemoteGit   code: 1,
26671 warn addRemoteGit   signal: null,
26671 warn addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
26672 info resetRemote resetting C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-polymerelements-test-fixture-git-a8830b55 for polymerelements/test-fixture
26673 silly gentlyRm C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-polymerelements-test-fixture-git-a8830b55 is being purged
26674 verbose gentlyRm don't care about contents; nuking C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-polymerelements-test-fixture-git-a8830b55
26675 silly vacuum-fs purging C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-polymerelements-test-fixture-git-a8830b55
26676 silly vacuum-fs quitting because other entries in C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes
26677 info git [ 'clone',
26677 info git   '--template=C:\\Users\\ghlongoane\\AppData\\Roaming\\npm-cache\\_git-remotes\\_templates',
26677 info git   '--mirror',
26677 info git   'https://github.com/polymerelements/test-fixture.git',
26677 info git   'C:\\Users\\ghlongoane\\AppData\\Roaming\\npm-cache\\_git-remotes\\git-https-github-com-polymerelements-test-fixture-git-a8830b55' ]
26678 error git clone --template=C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/polymerelements/test-fixture.git C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-polymerelements-test-fixture-git-a8830b55: Cloning into bare repository 'C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-polymerelements-test-fixture-git-a8830b55'...
26678 error git clone --template=C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/polymerelements/test-fixture.git C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-polymerelements-test-fixture-git-a8830b55: fatal: unable to access 'https://github.com/polymerelements/test-fixture.git/': Failed to connect to github.com port 443: Timed out
26679 silly trySSH attempting to clone git@github.com:polymerelements/test-fixture.git
26680 silly tryClone cloning polymerelements/test-fixture via git@github.com:polymerelements/test-fixture.git
26681 verbose tryClone git-github-com-polymerelements-test-fixture-git-8142662e not in flight; caching
26682 verbose correctMkdir C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes correctMkdir not in flight; initializing
26683 info git [ 'config', '--get', 'remote.origin.url' ]
26684 warn addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
26684 warn addRemoteGit
26684 warn addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
26684 warn addRemoteGit     at emitTwo (events.js:106:13)
26684 warn addRemoteGit     at ChildProcess.emit (events.js:191:7)
26684 warn addRemoteGit     at maybeClose (internal/child_process.js:877:16)
26684 warn addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
26684 warn addRemoteGit  polymerelements/test-fixture resetting remote C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-8142662e because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
26684 warn addRemoteGit
26684 warn addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
26684 warn addRemoteGit     at emitTwo (events.js:106:13)
26684 warn addRemoteGit     at ChildProcess.emit (events.js:191:7)
26684 warn addRemoteGit     at maybeClose (internal/child_process.js:877:16)
26684 warn addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
26684 warn addRemoteGit   killed: false,
26684 warn addRemoteGit   code: 1,
26684 warn addRemoteGit   signal: null,
26684 warn addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
26685 info resetRemote resetting C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-8142662e for polymerelements/test-fixture
26686 silly gentlyRm C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-8142662e is being purged
26687 verbose gentlyRm don't care about contents; nuking C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-8142662e
26688 silly vacuum-fs purging C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-8142662e
26689 silly vacuum-fs quitting because other entries in C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes
26690 info git [ 'clone',
26690 info git   '--template=C:\\Users\\ghlongoane\\AppData\\Roaming\\npm-cache\\_git-remotes\\_templates',
26690 info git   '--mirror',
26690 info git   'git@github.com:polymerelements/test-fixture.git',
26690 info git   'C:\\Users\\ghlongoane\\AppData\\Roaming\\npm-cache\\_git-remotes\\git-github-com-polymerelements-test-fixture-git-8142662e' ]
26691 error git clone --template=C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:polymerelements/test-fixture.git C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-8142662e: Cloning into bare repository 'C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-8142662e'...
26691 error git clone --template=C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:polymerelements/test-fixture.git C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-8142662e: Host key verification failed.
26691 error git clone --template=C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:polymerelements/test-fixture.git C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-8142662e: fatal: Could not read from remote repository.
26691 error git clone --template=C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:polymerelements/test-fixture.git C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-8142662e:
26691 error git clone --template=C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:polymerelements/test-fixture.git C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-8142662e: Please make sure you have the correct access rights
26691 error git clone --template=C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:polymerelements/test-fixture.git C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-8142662e: and the repository exists.
26692 silly fetchPackageMetaData Error: Command failed: git -c core.longpaths=true clone --template=C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:polymerelements/test-fixture.git C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-8142662e
26692 silly fetchPackageMetaData Cloning into bare repository 'C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-8142662e'...
26692 silly fetchPackageMetaData Host key verification failed.
26692 silly fetchPackageMetaData fatal: Could not read from remote repository.
26692 silly fetchPackageMetaData
26692 silly fetchPackageMetaData Please make sure you have the correct access rights
26692 silly fetchPackageMetaData and the repository exists.
26692 silly fetchPackageMetaData
26692 silly fetchPackageMetaData     at ChildProcess.exithandler (child_process.js:206:12)
26692 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
26692 silly fetchPackageMetaData     at ChildProcess.emit (events.js:191:7)
26692 silly fetchPackageMetaData     at maybeClose (internal/child_process.js:877:16)
26692 silly fetchPackageMetaData     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
26692 silly fetchPackageMetaData  error for test-fixture@github:polymerelements/test-fixture { Error: Command failed: git -c core.longpaths=true clone --template=C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:polymerelements/test-fixture.git C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-8142662e
26692 silly fetchPackageMetaData Cloning into bare repository 'C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-8142662e'...
26692 silly fetchPackageMetaData Host key verification failed.
26692 silly fetchPackageMetaData fatal: Could not read from remote repository.
26692 silly fetchPackageMetaData
26692 silly fetchPackageMetaData Please make sure you have the correct access rights
26692 silly fetchPackageMetaData and the repository exists.
26692 silly fetchPackageMetaData
26692 silly fetchPackageMetaData     at ChildProcess.exithandler (child_process.js:206:12)
26692 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
26692 silly fetchPackageMetaData     at ChildProcess.emit (events.js:191:7)
26692 silly fetchPackageMetaData     at maybeClose (internal/child_process.js:877:16)
26692 silly fetchPackageMetaData     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
26692 silly fetchPackageMetaData   killed: false,
26692 silly fetchPackageMetaData   code: 128,
26692 silly fetchPackageMetaData   signal: null,
26692 silly fetchPackageMetaData   cmd: 'git -c core.longpaths=true clone --template=C:\\Users\\ghlongoane\\AppData\\Roaming\\npm-cache\\_git-remotes\\_templates --mirror git@github.com:polymerelements/test-fixture.git C:\\Users\\ghlongoane\\AppData\\Roaming\\npm-cache\\_git-remotes\\git-github-com-polymerelements-test-fixture-git-8142662e' }
26693 silly rollbackFailedOptional Starting
26694 silly rollbackFailedOptional Finishing
26695 silly runTopLevelLifecycles Finishing
26696 silly install printInstalled
26697 verbose stack Error: Command failed: git -c core.longpaths=true clone --template=C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:polymerelements/test-fixture.git C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-8142662e
26697 verbose stack Cloning into bare repository 'C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-8142662e'...
26697 verbose stack Host key verification failed.
26697 verbose stack fatal: Could not read from remote repository.
26697 verbose stack
26697 verbose stack Please make sure you have the correct access rights
26697 verbose stack and the repository exists.
26697 verbose stack
26697 verbose stack     at ChildProcess.exithandler (child_process.js:206:12)
26697 verbose stack     at emitTwo (events.js:106:13)
26697 verbose stack     at ChildProcess.emit (events.js:191:7)
26697 verbose stack     at maybeClose (internal/child_process.js:877:16)
26697 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
26698 verbose cwd C:\MyTracker\ThinkTank\HelloPoly
26699 error Windows_NT 10.0.10586
26700 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "polymer-cli"
26701 error node v6.9.1
26702 error npm  v3.10.8
26703 error code 128
26704 error Command failed: git -c core.longpaths=true clone --template=C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:polymerelements/test-fixture.git C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-8142662e
26704 error Cloning into bare repository 'C:\Users\ghlongoane\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-8142662e'...
26704 error Host key verification failed.
26704 error fatal: Could not read from remote repository.
26704 error
26704 error Please make sure you have the correct access rights
26704 error and the repository exists.
26705 error If you need help, you may report this error at:
26705 error     <https://github.com/npm/npm/issues>
26706 verbose exit [ 1, true ]
```

**Comment by web-padawan** [comment]
@gifthlong try using this:
```
npm config set registry http://registry.npmjs.org/
npm set strict-ssl false
```

**Comment by gifthlong** [comment]
Thanks @web-padawan but i have already tried those and setting proxy - no luck :(

**Comment by codepic** [comment]
For me following [these steps](https://www.polymer-project.org/2.0/docs/tools/polymer-cli) fixed the issue. I believe the key to the solution was to reinstall Git.
