### ISSUE TITLE
Cannot find module 'browser-window'

### ISSUE THREAD

**Issue by ananyaojha** [Polymer/polymer-cli#404]
Uncaught Exception:
Error: Cannot find module 'browser-window'
    at Module._resolveFilename (module.js:440:15)
    at Function.Module._resolveFilename (/home/ananya/angular2desk/node_modules/electron-prebuilt/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ananya/angular2desk/index.js:2:21)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)

When I'm running npm start, Im getting this error.

index.js file - 
var app = require('electron').app;
var BrowserWindow = require('browser-window');

app.on('ready', ()=>{
	var mainWindow = new BrowserWindow({
		width: 1200,
		height:720
	})
});

package.json - 
{
  "name": "angular2desk",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "start": "electron ."
  },
  "author": "Ananya",
  "license": "MIT",
  "devDependencies": {
    "electron-prebuilt": "^1.3.5"
  },
  "dependencies": {
    "electron-prebuilt": "^1.3.5"
  },
  "description": ""
}

**Comment by ananyaojha** [comment]
FIXED
