### ISSUE TITLE
`polymer test` throws script error but `wct` runs fine

### ISSUE THREAD

**Issue by jaichandra** [Polymer/polymer-cli#445]
### Description
When I run `polymer test`, I see below script error (although all tests run ok). But if I run `wct` on the same set of tests, they pass without any error.

```
chrome 55 (203/0/2)                     safari 10.0 (202/0/2)                   firefox 46 (204/0/2)                  


Error: 2 failed tests

error:   Promise rejection: Error: 2 failed tests
error:   Error: 2 failed tests
    at /Users/<folders>/node_modules/web-component-tester/runner/steps.js:151:27
    at next (native)
    at fulfilled (/Users/<folders>/node_modules/web-component-tester/runner/steps.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
firefox 46               Error code ECONNRESET: Unexpected error. { Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at Socket.socketOnEnd (_http_client.js:344:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }
safari 10.0              Error code ECONNRESET: Unexpected error. { Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at Socket.socketOnEnd (_http_client.js:344:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }
```
### Versions & Environment
- Polymer CLI: v0.16.0
- node: v6.4.0
- Operating System: macOS Sierra

**Comment by FredKSchott** [comment]
Hmm, I haven't seen this before. Can you share the repo where this is happening, or create some simple steps that I could use to reproduce on my machine?
