### ISSUE TITLE
AssertionError: false == true 

### ISSUE THREAD

**Issue by rokity** [Polymer/polymer-cli#448]
I have this error when doing Polymer build .
error:   Uncaught exception: AssertionError: false == true
error:   AssertionError: false == true
    at Console.assert (console.js:95:23)
    at SplitFile.setPartContent (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/lib/polymer-project.js:173:17)
    at HtmlRejoiner._transform (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/lib/polymer-project.js:267:28)
    at HtmlRejoiner.Transform._read (_stream_transform.js:167:10)
    at HtmlRejoiner.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:333:12)
    at clearBuffer (_stream_writable.js:440:7)
    at onwrite (_stream_writable.js:372:7)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at afterTransform (_stream_transform.js:79:3)

Why I have this , I updated polymer and node for but it isn't work already.
Why this error?

**Comment by FredKSchott** [comment]
Regardless we should have a more friendly error message here.

I can't tell why this is happening from the code, can you share the repo where this is occurring? Or some simple steps that I could follow on my machine to reproduce? Otherwise we'll need to add some better debug logging so that we can find out what is wrong.

**Comment by rokity** [comment]
this is the repo 
https://github.com/rokity/mha
try to do bower install and polymer build
there is an error of syntax , in my script javascript but it isn't important.
The most important is the Assertion error.
Thanks for the help @FredKSchott

**Comment by faan11** [comment]
I found the problem: Polymer seems not support absolute path in building phase.

> <link rel="import" href="/bower_components/app-route/app-route.html">
