### ISSUE TITLE
"polymer test" command always return 0, even when tests are failing

### ISSUE THREAD

**Issue by jlagneau** [Polymer/polymer-cli#451]
The title is explicit. To reproduce this bug, I just added a failing test in the original file generated by "polymer init" like this:

```javascript
suite('blog-app', function() {
  // original test from "polymer init"
  test('instantiating the element works', function() {
    var element = fixture('basic');
    assert.equal(element.is, 'blog-app');
  });

  // test that should fail
  test('should fail', function() {
    assert.equal(true, false);
  });

});
```
and ran the test:
```
$ polymer test && echo "\n=====\n$?"
Installing and starting Selenium server for local browsers
Selenium server running on port 36815
Web server running on port 2000 and serving from /home/jlagneau/Works/Web/demo-spa
chrome 54                Beginning tests via http://localhost:2000/components/demo-spa/generated-index.html?cli_browser_id=0
404 GET /components/demo-spa/src/blog-app/components.html
chrome 54                ✖ test/blog-app/blog-app_test.html » blog-app » should fail

  expected true to equal false
    <unknown> at   Context.<anonymous> at blog-app_test.html:30:0

chrome 54                Tests failed: 1 failed tests
Test run ended in failure: 1 failed tests

chrome 54 (1/0/1)                     


Error: 1 failed tests

error:   Promise rejection: Error: 1 failed tests
error:   Error: 1 failed tests
    at /home/jlagneau/.nvm/versions/node/v6.8.1/lib/node_modules/web-component-tester/runner/steps.js:151:27
    at next (native)
    at fulfilled (/home/jlagneau/.nvm/versions/node/v6.8.1/lib/node_modules/web-component-tester/runner/steps.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)

=====
0
```
wct return is all right but polymer test isn't. Is that the intended behavior ?

**Comment by FredKSchott** [comment]
This was resolved in https://github.com/Polymer/polymer-cli/pull/418, we will release this in a new version soon

**Comment by jlagneau** [comment]
Thanks for the fast reply, I'm closing it since it's already fixed. Sorry for the duplication, I only searched in open issues. My bad.
