### ISSUE TITLE
`polymer test -l chrome` throws a `ECONNRESET` error on macOS Sierra

### ISSUE THREAD

**Issue by hguiney** [Polymer/polymer-cli#468]
### Description
`polymer test -l chrome` throws a `ECONNRESET` error. Have tried this within my own project and within the Polymer Starter Kit.

### Versions & Environment
- Polymer CLI: 0.17.0
- node: v6.1.0
- Operating System: macOS Sierra 10.12.1 (16B2555)

#### Steps to Reproduce
1. Create a Starter Kit project: `polymer init starter-kit`
2. Run `polymer test -l chrome`

#### Expected Results
Tests complete and indicate pass or fail for Chrome.

#### Actual Results
Error is thrown:

> $ polymer test -l chrome
> Installing and starting Selenium server for local browsers
> Selenium server running on port 57982
> Web server running on port 2000 and serving from /Users/Hugh/Sites/polymer-starter-kit
> chrome 54                Beginning tests via http://localhost:2000/components/polymer-starter-kit/generated-index.html?cli_browser_id=0
> chrome 54                Tests passed
> Test run ended with great success
> 
> chrome 54 (2/0/0)
> 
> chrome 54                Error code ECONNRESET: Unexpected error. { Error: socket hang up
>     at createHangUpError (_http_client.js:250:15)
>     at Socket.socketOnEnd (_http_client.js:342:23)
>     at emitNone (events.js:91:20)
>     at Socket.emit (events.js:185:7)
>     at endReadableNT (_stream_readable.js:926:12)
>     at _combinedTickCallback (internal/process/next_tick.js:74:11)
>     at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }
> chrome failed to maximize
> 
> chrome 54 (2/0/0)

**Comment by FredKSchott** [comment]
I'm still on El Capitan and cannot reproduce. @justinfagnani @rictic @usergenic anyone on sierra who can try reproducing?

**Comment by cherukumilli** [comment]
@FredKSchott 

I see the same error on my macOS Sierra:

```
chrome 54 (24/0/0)                    

chrome 54                Error code ECONNRESET: Unexpected error. { Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at Socket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }
chrome failed to maximize
```

**Comment by justinfagnani** [comment]
Working on Sierra for me, but I have Chrome 55. Is it a webdriver issue?

**Comment by dsnowdon** [comment]
Getting on both

node -v
v6.9.1

macOS Sierra 10.12.1


$ polymer test -l chrome
Installing and starting Selenium server for local browsers
Selenium server running on port 53339
Web server running on port 2000 and serving from /Users/dale/Desktop/forms-spread
chrome 54                Beginning tests via http://localhost:2000/components/forms-spread/generated-index.html?cli_browser_id=0
chrome 54                Tests passed
Test run ended with great success

chrome 54 (1/0/0)                     

chrome 54                Error code ECONNRESET: Unexpected error. { Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at Socket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }
chrome failed to maximize
$ clear
chrome 54 (1/0/0)                     

$ polymer test -l chrome
Installing and starting Selenium server for local browsers
Selenium server running on port 53583
Web server running on port 2000 and serving from /Users/dale/Desktop/forms-spread
chrome 55                Beginning tests via http://localhost:2000/components/forms-spread/generated-index.html?cli_browser_id=0
chrome 55                Tests passed
Test run ended with great success

chrome 55 (1/0/0)                     

chrome 55                Error code ECONNRESET: Unexpected error. { Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at Socket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }
chrome failed to maximize
$

**Comment by dsnowdon** [comment]
Any updates for this?

**Comment by rictic** [comment]
We're totally unable to reproduce this error, making it fairly hard to track down.

**Comment by FredKSchott** [comment]
Have you tried uninstalling, and then re-installing the CLI? The Sierra upgrade could have messed with some compiled npm dependencies that polymer-cli relies on, like `sauce`. Uninstalling all npm global packages and clearing your cache may help as well.

**Comment by dsnowdon** [comment]
Removing all my NPM packages and re-installing, makes Chrome and Firefox work! It's still hanging on Safari.

Thanks for the suggestion

**Comment by fafcrumb** [comment]
Getting all sorts of issues on sierra 10.12.3 with safari 10.0.3, chrome 57, node 6.10.0, and polymer cli 0.18.0-pre.13. Chrome gives the error above when using the global cli, but hangs when using local web-component-tester 5.0. Safari hangs on both.

**Comment by silenceisgolden** [comment]
Also getting this error using sierra and the polymer 2.0 preview cli build.

**Comment by silenceisgolden** [comment]
Try enabling automation in Safari. However even with this enabled I get:

```
firefox 53               Error code ECONNRESET: Unexpected error. { Error: socket hang up
    at createHangUpError (_http_client.js:302:15)
    at Socket.socketOnEnd (_http_client.js:394:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9) code: 'ECONNRESET' }
firefox failed to maximize
chrome 60                Error code ECONNRESET: Unexpected error. { Error: socket hang up
    at createHangUpError (_http_client.js:302:15)
    at Socket.socketOnEnd (_http_client.js:394:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9) code: 'ECONNRESET' }
chrome failed to maximize
chrome 58                Error code ECONNRESET: Unexpected error. { Error: socket hang up
    at createHangUpError (_http_client.js:302:15)
    at Socket.socketOnEnd (_http_client.js:394:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9) code: 'ECONNRESET' }
chrome failed to maximize
safari 10.1              Error code ECONNRESET: Unexpected error. { Error: socket hang up
    at createHangUpError (_http_client.js:302:15)
    at Socket.socketOnEnd (_http_client.js:394:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9) code: 'ECONNRESET' }
safari failed to maximize
```

All tests do pass, node v7.10.0, Sierra 10.12.4

**Comment by ArthurJahn** [comment]
Same issue here
node v8.1.2
MacOS Sierra 10.12.5

```
Installing and starting Selenium server for local browsers
Selenium server running on port 54027
chrome 59                Beginning tests via http://localhost:8000/components/webapp/generated-index.html?cli_browser_id=0
firefox 53               Beginning tests via http://localhost:8000/components/webapp/generated-index.html?cli_browser_id=1
chrome 59                Tests passed
chrome failed to maximize
firefox 53               Tests passed
Test run ended with great success

chrome 59 (78/0/0)                      firefox 53 (78/0/0)

chrome 59                Error code ECONNRESET: Unexpected error. { Error: socket hang up
    at createHangUpError (_http_client.js:344:15)
    at Socket.socketOnEnd (_http_client.js:436:23)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9) code: 'ECONNRESET' }
firefox 53               Error code ECONNRESET: Unexpected error. { Error: socket hang up
    at createHangUpError (_http_client.js:344:15)
    at Socket.socketOnEnd (_http_client.js:436:23)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9) code: 'ECONNRESET' }
firefox failed to maximize
```

**Comment by silenceisgolden** [comment]
Still an issue

MacOS 10.12.5
node v8.1.3

```
> polymer test
Installing and starting Selenium server for local browsers
Selenium server running on port 53790
safari 10.1.1            Beginning tests via http://localhost:8081/components/button-design/generated-index.html?cli_browser_id=3
chrome 61                Beginning tests via http://localhost:8081/components/button-design/generated-index.html?cli_browser_id=0
firefox 53               Beginning tests via http://localhost:8081/components/button-design/generated-index.html?cli_browser_id=2
safari 10.1.1            Tests passed
chrome 59                Beginning tests via http://localhost:8081/components/button-design/generated-index.html?cli_browser_id=1
chrome 61                Tests passed
chrome 59                Tests passed
firefox 53               Tests passed
Test run ended with great success

chrome 61 (2/0/0)                       chrome 59 (2/0/0)                       firefox 53 (2/0/0)                      safari 10.1.1 (2/0/0)                 

chrome 61                Error code ECONNRESET: Unexpected error. { Error: socket hang up
    at createHangUpError (_http_client.js:344:15)
    at Socket.socketOnEnd (_http_client.js:436:23)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9) code: 'ECONNRESET' }
chrome failed to maximize
firefox 53               Error code ECONNRESET: Unexpected error. { Error: socket hang up
    at createHangUpError (_http_client.js:344:15)
    at Socket.socketOnEnd (_http_client.js:436:23)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9) code: 'ECONNRESET' }
firefox failed to maximize
chrome 59                Error code ECONNRESET: Unexpected error. { Error: socket hang up
    at createHangUpError (_http_client.js:344:15)
    at Socket.socketOnEnd (_http_client.js:436:23)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9) code: 'ECONNRESET' }
chrome failed to maximize
safari 10.1.1            Error code ECONNRESET: Unexpected error. { Error: socket hang up
    at createHangUpError (_http_client.js:344:15)
    at Socket.socketOnEnd (_http_client.js:436:23)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9) code: 'ECONNRESET' }
safari failed to maximize
```
