### ISSUE TITLE
Polymer init not working

### ISSUE THREAD

**Issue by jordyvandomselaar** [Polymer/polymer-cli#479]
### Description
Polymer init  not working as intented

### Versions & Environment

- Polymer CLI: 0.17/0
- node: 7.1
- Operating System: windows 10

#### Steps to Reproduce

1. Run `polymer init`
#### Expected Results

No error is thrown, Polymer inits as intended

#### Actual Results

I get an error.

##### Stacktrace:
```PS C:\Users\jordy\Documents\apps\electron\irc> polymer init
'uname' is not recognized as an internal or external command,
operable program or batch file.
error:   cli runtime exception: Error: write EINVAL
error:   Error: write EINVAL
    at exports._errnoException (util.js:1022:11)
    at WriteStream.Socket._writeGeneric (net.js:715:26)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)

    at WriteStream.Socket.write (net.js:661:40)
    at MuteStream.ondata (stream.js:31:26)
    at emitOne (events.js:96:13)
    at MuteStream.emit (events.js:188:7)
error:   Promise rejection: Error: This socket is closed
error:   Error: This socket is closed
    at WriteStream.Socket._writeGeneric (net.js:683:19)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at Console.log (console.js:43:16)
    at module.exports.UI.onForceClose (C:\Users\jordy\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\inquirer\lib\ui\baseUI.js:3
2:11)
    at emitOne (events.js:101:20)
    at process.emit (events.js:188:7)```

**Comment by FredKSchott** [comment]
This is only a bug on the `next` branch. A fix has been pushed to master and will be out with the next `next` release.

**Comment by FredKSchott** [comment]
Now fixed on the latest `next` branch, you can get it with `npm install -g polymer-cli@next`
