### ISSUE TITLE
Using invalid JavaScript with a marked-element script tag throws Uglify errors

### ISSUE THREAD

**Issue by deltaepsilon** [Polymer/polymer-cli#546]
### Description
Markdown is not valid JavaScript, so using it within a <marked-element> script tag, even with type="text/markdown" drives Uglify crazy, breaking the ```polymer build```.

### Versions & Environment
Polymer CLI v0.17.0
Node v6.9.1
OS X

#### Steps to Reproduce
1. Create an app and add a marked-element. Put something in it like this:

```
<link rel="import" href="../../bower_components/polymer/polymer.html">
<link rel="import" href="../../bower_components/marked-element/marked-element.html">
<link rel="import" href="../shared-styles.html">

<dom-module id="about-view">
  <template>
    <style include="shared-styles">
      :host {
        display: block;
      }
    </style>
    
    <marked-element>
      <div class="markdown-html"></div>
      <script type="text/markdown">
        #About View
      </script>
    </marked-element>

  </template>
  <script>
    Polymer({
       is: "about-view",
    });
  </script>
</dom-module>
```
2. Run ```polymer build```

#### Expected Results
Beautiful logs

#### Actual Results
```
warn:    Unable to optimize .js file /Users/quiver/Development/quiver-timer/src/views/about-view.html_script_0.js 

{ err: 
   { message: 'SyntaxError: Unexpected character \'#\'',
     filename: 0,
     line: 2,
     col: 8,
     pos: 9,
     stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1547:18)\n    at js_error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1555:11)\n    at parse_error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1679:9)\n    at Object.next_token [as input] (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1951:9)\n    at next (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2080:25)\n    at Object.parse (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2066:15)\n    at addFile (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:72:33)\n    at /usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:81:17\n    at Array.forEach (native)\n    at Object.exports.minify (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:79:26)' } }
info:    Build complete!

```

**Comment by FredKSchott** [comment]
This has been fixed in the latest version of polymer-build. Try `npm install polymer-cli@next` to get the latest version with this fix.
