### ISSUE TITLE
polymer-2-application template fails testing

### ISSUE THREAD

**Issue by mattpalermo** [Polymer/polymer-cli#657]
### Description

Running `polymer test` on a fresh polymer-2-application template results in 1 failed test.

### Versions & Environment

- Polymer CLI: 0.18.0-pre.15
- node: v6.10.2
- Operating System: Ubuntu 16.10 (17.04 is meant to be released today. Whoo!)

#### Steps to Reproduce

1. Create a polymer 2 application project: `polymer init polymer-2-application`
2. Install wct as a local project dependency as per the recommendation logged by wct: `npm install --save-dev web-component-tester` (This doesn't affect the error result)
2. Run the tests: `polymer test`

#### Expected Results

The test should pass.

#### Actual Results

The test did not pass. The following was logged to the terminal:

```
matt@matt-P552LA:polytest$ polymer test
Installing and starting Selenium server for local browsers
Selenium server running on port 34767
firefox 52               Beginning tests via http://localhost:8081/components/polytest/generated-index.html?cli_browser_id=0
firefox failed to maximize
firefox 52               ✖ test/polytest-app/polytest-app_test.html » polytest-app » instantiating the element works

  expected undefined to equal 'polytest-app'
    <unknown> at                             AssertionError at /components/chai/chai.js:5553:0
    <unknown> at   [3]</module.exports/Assertion.prototype.assert at /components/chai/chai.js:206:0
    <unknown> at           [6]</module.exports/assert.equal at /components/chai/chai.js:2277:0
    <unknown> at                                  <unknown> at polytest-app_test.html:25:0

firefox 52               Tests failed: 1 failed tests
Test run ended in failure: 1 failed tests

firefox 52 (0/0/1)                    


Error: 1 failed tests

error:   cli runtime exception: Error: 1 failed tests
error:   Error: 1 failed tests
    at /usr/lib/node_modules/polymer-cli/node_modules/web-component-tester/runner/steps.js:170:27
    at next (native)
    at fulfilled (/usr/lib/node_modules/polymer-cli/node_modules/web-component-tester/runner/steps.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by mattpalermo** [comment]
Sorry, I forgot to search for existing issues before posting.
This problem is documented in issue #603.
