### ISSUE TITLE
Installation with Yarn global crashes `polymer test`

### ISSUE THREAD

**Issue by TimvdLippe** [Polymer/polymer-cli#666]
### Description

I install the polymer-cli with Yarn (`yarn global add polymer-cli@next`), but it seems to crash when running `polymer test` on a new project.

### Versions & Environment
- Polymer CLI: polymer-cli@0.18.0-pre.15
- node: v7.7.3
- Operating System: Ubuntu 16.04

#### Steps to Reproduce

1. `yarn global add polymer-cli@next`
2. `mkdir psk && cd psk && polymer init` to install `polymer-2-starter-kit`
3. `polymer test`

#### Expected Results

Tests run with web-component-tester.

#### Actual Results

```js
tim@tim-HP-ZBook-15:~/Projects/psk$ polymer test
error:   cli runtime exception: Error: Cannot find module '../build/safe-execute'
error:   Error: Cannot find module '../build/safe-execute'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/tim/.config/yarn/global/node_modules/wd/lib/commands.js:21:27)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

Installation with `npm install -g polymer-cli@next` and the other reproduction steps works just fine. It seems that the post-install commands are not invoked when installing with `Yarn`?

**Comment by TimvdLippe** [comment]
Okay a quick update: I had removed my Yarn installation to test if it worked with `npm`. It seems that installing the cli on a new machine works. However, when updating the version (e.g. you already did `yarn global add` and then you do `yarn global add` again) does break it. So the installation steps are only executed on the first installation and not for every update.

**Comment by FredKSchott** [comment]
@TimvdLippe hmm, I can't reproduce on my machine. Can you clear your yarn cache (`yarn cache clean`) and try reinstalling? Or did your second comment mean that you can no longer reproduce?

**Comment by TimvdLippe** [comment]
@FredKSchott Hm, neither can I at the moment. Which is really weird, because I could yesterday. I will continue trying to find reproduction steps and else close this issue.

**Comment by TimvdLippe** [comment]
@gijsweterings just encountered a similar issue, but now with `polymer init` :sob:

**Comment by limonte** [comment]
This weird exception was happening in our Travis CI build with **enabled npm cache**. If there's node_modules folder in cache which was generated by npm, you will face the exception.

The solution is to clear all Travis caches before switching from npm to yarn:

1. ![](https://i.imgur.com/6TeaRnx.png)

2. ![](https://i.imgur.com/YOkZG8n.png)

**Comment by bennypowers** [comment]
solved this with `yarn global remove phantomjs`

**Comment by pedro2555** [comment]
I'm facing this issue and no `yarn` to be seen.

```bash
npm install -g polymer-cli
mkdir polymer-test
cd polymer-test

polymer init

polymer test
```

and results in the exact same:

```
error: [cli.main]   cli runtime exception: Error: Cannot find module '../build/safe-execute'
error: [cli.main]   Error: Cannot find module '../build/safe-execute'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/wd/lib/commands.js:22:27)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
```

Not exactly sure what information I can give that is of any help... Feel free to ask, actually very glad if you do.

- Bash on Ubuntu on Windows

- Polymer 2 Starter Kit
