### ISSUE TITLE
paper-button won't appear in polymer 2 element template (finicky import paths)

### ISSUE THREAD

**Issue by wmginsberg** [Polymer/polymer-cli#668]
### Description
Trying to use a paper button in element from polymer 2 element template on chrome, and it's not showing up. Import paths are being weird. 
*I could be making a major mistake, but I'm filing it anyway, since it wasn't (and still isn't) clear to me how to fix it 

### Versions & Environment
- Polymer CLI: 0.18.0-pre.13
- node: v6.4.0
- Operating System: macOS Sierra 10.12.3

#### Expected Results
A raised paper button appears with the click text

#### Actual Results
No button appears

NOTE: if I change the path to include bower_components/ like i've done in other components, I get a ton of errors... see here (yes, element is named yoda-speak and it's a very useful element ->

analyzer.js:342 Ignoring duplicate element definition: undefined (11 of these in yellow, and then the rest below in red)
analyzer.js:331 Uncaught (in promise) Error: Error parsing script in http://127.0.0.1:8081/components/yoda-speak/bower_components/polymer/lib/legacy/class.html at NaN:NaN
TypeError: Cannot read property 'forEach' of undefined
    at Object.enterMethodDefinition (http://127.0.0.1:8081/components/hydrolysis/hydrolysis.js:1947:38)
    at applyVisitors (http://127.0.0.1:8081/components/hydrolysis/hydrolysis.js:2405:51)
    at Controller.enter (http://127.0.0.1:8081/components/hydrolysis/hydrolysis.js:2428:20)
    at Controller.__execute (http://127.0.0.1:8081/components/hydrolysis/hydrolysis.js:25168:31)
    at Controller.traverse (http://127.0.0.1:8081/components/hydrolysis/hydrolysis.js:25266:28)
    at Object.traverse (http://127.0.0.1:8081/components/hydrolysis/hydrolysis.js:25478:27)
    at Object.jsParse (http://127.0.0.1:8081/components/hydrolysis/hydrolysis.js:2449:16)
    at Analyzer._processScript (http://127.0.0.1:8081/components/hydrolysis/hydrolysis.js:319:43)
    at http://127.0.0.1:8081/components/hydrolysis/hydrolysis.js:302:44..... etc.

**Comment by justinfagnani** [comment]
@wmginsberg I'm not clear on your setup and code here. Can you make a reproduction for us to look at?
