### ISSUE TITLE
Error analyzing app with iron-flex-layout

### ISSUE THREAD

**Issue by stramel** [Polymer/polymer-cli#691]
### Description

When running `polymer analyze` on my app root directory it results in errors in the build directory.

### Versions & Environment

- Polymer CLI: 0.18.1
- node: 6.9.1
- Operating System: Windows 10
- Terminal: Git Bash (MINGW64)

#### Steps to Reproduce

1. Download https://github.com/jay8t6/lazy-import-bundle
2. `npm i -g polymer-cli`
3. `npm i; polymer install`
4. `npm run build` (Will fail if skipping 4a but still reproduces regardless)
4a. (Optionally), comment out line no 17 in `src/pages/my-page-view2/my-page-view2.html`
4b. If 4a was done, `npm run build`
5. `polymer analyze`

#### Expected Results

Generates an analyzed JSON representation of my project

#### Actual Results

```
$ polymer analyze
error:   Promise rejection: Error: Error parsing build/bower_components/iron-flex-layout/iron-flex-layout.html:
 TypeError: Cannot read property 'is' of null
    at Parser.parseDeclarationOrRuleset (C:\Users\stramema\AppData\Roaming\nvm\v6.9.1\node_modules\polymer-cli\node_modules\shady-css-parser\dist\shady-css\parser.js:206:37)
    at Parser.parseRule (C:\Users\stramema\AppData\Roaming\nvm\v6.9.1\node_modules\polymer-cli\node_modules\shady-css-parser\dist\shady-css\parser.js:80:21)
    at Parser.parseRulelist (C:\Users\stramema\AppData\Roaming\nvm\v6.9.1\node_modules\polymer-cli\node_modules\shady-css-parser\dist\shady-css\parser.js:153:27)
    at Parser.parseDeclarationOrRuleset (C:\Users\stramema\AppData\Roaming\nvm\v6.9.1\node_modules\polymer-cli\node_modules\shady-css-parser\dist\shady-css\parser.js:213:87)
    at Parser.parseRule (C:\Users\stramema\AppData\Roaming\nvm\v6.9.1\node_modules\polymer-cli\node_modules\shady-css-parser\dist\shady-css\parser.js:80:21)
    at Parser.parseRules (C:\Users\stramema\AppData\Roaming\nvm\v6.9.1\node_modules\polymer-cli\node_modules\shady-css-parser\dist\shady-css\parser.js:62:25)
    at Parser.parseStylesheet (C:\Users\stramema\AppData\Roaming\nvm\v6.9.1\node_modules\polymer-cli\node_modules\shady-css-parser\dist\shady-css\parser.js:55:47)
    at Parser.parse (C:\Users\stramema\AppData\Roaming\nvm\v6.9.1\node_modules\polymer-cli\node_modules\shady-css-parser\dist\shady-css\parser.js:51:19)
    at CssParser.parse (C:\Users\stramema\AppData\Roaming\nvm\v6.9.1\node_modules\polymer-cli\node_modules\polymer-analyzer\lib\css\css-parser.js:23:34)
    at AnalysisContext._parseContents (C:\Users\stramema\AppData\Roaming\nvm\v6.9.1\node_modules\polymer-cli\node_modules\polymer-analyzer\lib\core\analysis-context.js:412:27)
error:   Error: Error parsing build/bower_components/iron-flex-layout/iron-flex-layout.html:
 TypeError: Cannot read property 'is' of null
    at Parser.parseDeclarationOrRuleset (C:\Users\stramema\AppData\Roaming\nvm\v6.9.1\node_modules\polymer-cli\node_modules\shady-css-parser\dist\shady-css\parser.js:206:37)
    at Parser.parseRule (C:\Users\stramema\AppData\Roaming\nvm\v6.9.1\node_modules\polymer-cli\node_modules\shady-css-parser\dist\shady-css\parser.js:80:21)
    at Parser.parseRulelist (C:\Users\stramema\AppData\Roaming\nvm\v6.9.1\node_modules\polymer-cli\node_modules\shady-css-parser\dist\shady-css\parser.js:153:27)
    at Parser.parseDeclarationOrRuleset (C:\Users\stramema\AppData\Roaming\nvm\v6.9.1\node_modules\polymer-cli\node_modules\shady-css-parser\dist\shady-css\parser.js:213:87)
    at Parser.parseRule (C:\Users\stramema\AppData\Roaming\nvm\v6.9.1\node_modules\polymer-cli\node_modules\shady-css-parser\dist\shady-css\parser.js:80:21)
    at Parser.parseRules (C:\Users\stramema\AppData\Roaming\nvm\v6.9.1\node_modules\polymer-cli\node_modules\shady-css-parser\dist\shady-css\parser.js:62:25)
    at Parser.parseStylesheet (C:\Users\stramema\AppData\Roaming\nvm\v6.9.1\node_modules\polymer-cli\node_modules\shady-css-parser\dist\shady-css\parser.js:55:47)
    at Parser.parse (C:\Users\stramema\AppData\Roaming\nvm\v6.9.1\node_modules\polymer-cli\node_modules\shady-css-parser\dist\shady-css\parser.js:51:19)
    at CssParser.parse (C:\Users\stramema\AppData\Roaming\nvm\v6.9.1\node_modules\polymer-cli\node_modules\polymer-analyzer\lib\css\css-parser.js:23:34)
    at AnalysisContext._parseContents (C:\Users\stramema\AppData\Roaming\nvm\v6.9.1\node_modules\polymer-cli\node_modules\polymer-analyzer\lib\core\analysis-context.js:412:27)
    at AnalysisContext._parseContents (C:\Users\stramema\AppData\Roaming\nvm\v6.9.1\node_modules\polymer-cli\node_modules\polymer-analyzer\lib\core\analysis-context.js:418:19)
    at AnalysisContext.<anonymous> (C:\Users\stramema\AppData\Roaming\nvm\v6.9.1\node_modules\polymer-cli\node_modules\polymer-analyzer\lib\core\analysis-context.js:360:44)
    at next (native)
    at fulfilled (C:\Users\stramema\AppData\Roaming\nvm\v6.9.1\node_modules\polymer-cli\node_modules\polymer-analyzer\lib\core\analysis-context.js:17:58)
```

**Comment by rictic** [comment]
Hm, I followed those instructions and I didn't see an issue. I ran at commit 9a65369e924e424ec5d5057863161a2c29de07e5 from lazy-import-bundle

I also ran `npm run build` and though it failed it did produce a build directory. Even then I didn't get the above error.

**Comment by stramel** [comment]
Ummm let me double-check the steps to reproduce, sorry. Will update

**Comment by stramel** [comment]
Not getting this issue anymore with

**Polymer CLI:** 1.6.0
**Node:** 8.9.4
