### ISSUE TITLE
Getting TypeError when starting a new project

### ISSUE THREAD

**Issue by andreyluiz** [Polymer/polymer-cli#715]
### Description
When I try to create a new project running `polymer init` and select a template I get a TypeError.

### Versions & Environment

- Polymer CLI: 0.18.1
- node: v6.9.4
- Operating System: Ubuntu 16.04

#### Steps to Reproduce
1. Create a new directory a cd into it;
2. Run `polymer init`;
3. Select any of the options.

#### Expected Results
I should be able to write the name of the element and proceed the entire setup until the element/application creation.

#### Actual Results
I get the following error right after selecting the template:

```
? Element name (my-el) error:   Uncaught exception: TypeError: this.env.adapter.prompt(...).then is not a function
error:   TypeError: this.env.adapter.prompt(...).then is not a function
    at ElementGenerator.Base.prompt (/home/andrey/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:168:45)
    at ElementGenerator.<anonymous> (/home/andrey/.config/yarn/global/node_modules/polymer-cli/lib/init/element/element.js:72:41)
    at next (native)
    at /home/andrey/.config/yarn/global/node_modules/polymer-cli/lib/init/element/element.js:19:71
    at __awaiter (/home/andrey/.config/yarn/global/node_modules/polymer-cli/lib/init/element/element.js:15:12)
    at ElementGenerator.prompting (/home/andrey/.config/yarn/global/node_modules/polymer-cli/lib/init/element/element.js:50:20)
    at Object.<anonymous> (/home/andrey/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:417:23)
    at /home/andrey/.config/yarn/global/node_modules/yeoman-generator/node_modules/run-async/index.js:25:25
    at /home/andrey/.config/yarn/global/node_modules/yeoman-generator/node_modules/run-async/index.js:24:19
    at /home/andrey/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:418:9
```

**Comment by FredKSchott** [comment]
We recently released Polymer CLI v1, not sure if this is still an issue. Can you reproduce in the latest version?
