### ISSUE TITLE
error [unknown-superclass] - Unable to resolve superclass Array

### ISSUE THREAD

**Issue by atolk** [Polymer/polymer-cli#734]
### Description
Polymer build unable to resolve superclass when subclassing from built-in objects.

### Versions & Environment
- Polymer CLI: 0.18.3
- node: 7.9.0
#### Steps to Reproduce
1. Create an application project: `polymer init polymer-2-starter-kit`
2. In the _src_ directory create files:
- MyArray.html:
`<script src='MyArray.js'></script>`
- MyArray.js:
`class MyArray extends Array {}`
3. Add on top to the my-app.html:
`<link rel="import" href="MyArray.html">`
4. Build: `polymer build`

#### Expected Results
No error is throw

#### Actual Results
class MyArray extends Array {}
                      ~~~~~

src/MyArray.js(0,22) error [unknown-superclass] - Unable to resolve superclass Array
error:   Promise rejection: Error: 1 error(s) occurred during build.
error:   Error: 1 error(s) occurred during build.
    at BuildAnalyzer._done (/usr/lib/node_modules/polymer-cli/node_modules/polymer-build/lib/analyzer.js:229:36)
    at BuildAnalyzer.<anonymous> (/usr/lib/node_modules/polymer-cli/node_modules/polymer-build/lib/analyzer.js:189:26)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/polymer-cli/node_modules/polymer-build/lib/analyzer.js:17:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by justinfagnani** [comment]
cc @e111077
