### ISSUE TITLE
polymer command errors

### ISSUE THREAD

**Issue by tw1t611** [Polymer/polymer-cli#776]
### Description

polymer command errors
polymer serve shows the same result
I reinstalled polymer-cli: npm [un]install -g polymer-cli

It was working fine until I restarted the polymer serve job. 

### Versions & Environment

- Polymer CLI: 1.1.0
- node: 6.0
- Operating System: arch linux x64

#### Steps to Reproduce

$ polymer 

#### Expected Results
No error is thrown

#### Actual Results
error:   Promise rejection: SyntaxError: Unexpected token ] in JSON at position 140
error:   SyntaxError: Unexpected token ] in JSON at position 140
    at JSON.parse (<anonymous>)
    at Function.loadOptionsFromFile (/usr/lib/node_modules/polymer-cli/node_modules/polymer-project-config/lib/index.js:166:35)
    at new PolymerCli (/usr/lib/node_modules/polymer-cli/lib/polymer-cli.js:86:56)
    at Object.<anonymous> (/usr/lib/node_modules/polymer-cli/lib/run.js:35:17)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/polymer-cli/lib/run.js:20:71
    at __awaiter (/usr/lib/node_modules/polymer-cli/lib/run.js:16:12)
    at __dirname (/usr/lib/node_modules/polymer-cli/lib/run.js:33:8)
    at Object.<anonymous> (/usr/lib/node_modules/polymer-cli/lib/run.js:50:4)
    at Module._compile (module.js:571:32)

**Comment by aomarks** [comment]
Can you paste your polymer.json? Maybe it has a typo in it?

**Comment by tw1t611** [comment]
I'm sorry, there was one..

**Comment by FredKSchott** [comment]
@tm1t611 I'm sorry I don't understand, what do you mean?

That error most likely means there is a bad polymer.json in your project.

**Comment by tw1t611** [comment]
I meant, there was a typo in the polymer.json.
I'll close this.
