### ISSUE TITLE
polymer build fails at random

### ISSUE THREAD

**Issue by gudatcomputers** [Polymer/polymer-cli#780]
### Description
`polymer build` generates seemingly random failures.  With no changes to the repository, the same `polymer build` will succeed, and other times it will fail.  It seems to succeed a few times in a row, and then fail a few times in a row. I've included the build section of my `polymer.json` below.  I can cause the build to generate the same error by setting `bundle:false` in my es6 build.

### Versions & Environment
- Polymer CLI: 1.1.0
- node: 6.9.1
- Operating System: MacOS 10.11.6 

#### Steps to Reproduce
1. `polymer build`

#### Expected Results
build does not fail

#### Actual Results
```
error:   Promise rejection: AssertionError: false == true
error:   AssertionError: false == true
    at Console.assert (console.js:95:23)
    at SplitFile.setPartContent (/Users/gudatcomputers/.nvm/versions/node/v6.9.1/lib/node_modules/polymer-cli/node_modules/polymer-build/lib/html-splitter.js:120:17)
    at HtmlRejoinTransform._transformIter_2 (/Users/gudatcomputers/.nvm/versions/node/v6.9.1/lib/node_modules/polymer-cli/node_modules/polymer-build/lib/html-splitter.js:227:40)
    at next (native)
    at resume (/Users/gudatcomputers/.nvm/versions/node/v6.9.1/lib/node_modules/polymer-cli/node_modules/polymer-build/lib/html-splitter.js:34:44)
    at fulfill (/Users/gudatcomputers/.nvm/versions/node/v6.9.1/lib/node_modules/polymer-cli/node_modules/polymer-build/lib/html-splitter.js:36:31)
    at process._tickCallback (internal/process/next_tick.js:103:7)
Process exited with code 1
```

related build section of `polymer.json`
```
"builds": [
    {
      "name": "es5",

      "js": {
        "minify": true,
        "compile": true
      },
      "css": {
        "minify": true
      },
      "html": {
        "minify": true
      }
    },
    {
      "name": "es6",
      "bundle": true,
      "js": {
        "minify": true
      },
      "css": {
        "minify": true
      },
      "html": {
        "minify": true
      }
    }
  ]
```

**Comment by FredKSchott** [comment]
Sounds like a race condition :/ We haven't encountered this ourselves yet and can't reproduce, so this will be hard to debug without your actual code base or more info. But a definite action item here for today is to fix that assertion error to be more helpful.

**Comment by gudatcomputers** [comment]
Yeah that was what we thought too.  I could provide codebase with modifications.  Since we're developing an internal component that interacts with internal APIs via iron-ajax I wouldn't want to hand that out in its current state.  Would that be valuable?

**Comment by antoinegoutagny** [comment]
Has there been any progress on this issue? I'm running into it in maybe 90% of my builds. See this [SO question](https://stackoverflow.com/questions/48442943/polymer-build-file-save-error) for details.
