### ISSUE TITLE
Polymer 1 Bundled builds fail

### ISSUE THREAD

**Issue by milesje** [Polymer/polymer-cli#849]
### Description
Polymer 1.X build with bundle: true fails.

### Versions & Environment
- Polymer CLI: 1.4.1
- node: 8.4
- Operating System: Windows 10

#### Steps to Reproduce
1. polymer build - with bundle: true (or use one of the bundled presets)

#### Expected Results
Build completes

#### Actual Results
build errors out. If you disable bundle or use an unbundled preset it builds fine.

**Comment by milesje** [comment]
Here is a copy of my polymer.json
```
{
  "entrypoint": "index.html",
  "shell": "src/netd-auth.html",
  "fragments": [
    "src/add-user.html",
    "src/apps-view.html",
    "src/change-password.html",
    "src/create-role.html",
    "src/forgot-password.html",
    "src/login-view.html",
    "src/netd-app.html",
    "src/profile-view.html",
    "src/reset-password.html",
    "src/roles-view.html",
    "src/users-view.html"
  ],
  "sources": [
    "src/**/*",
    "images/**/*",
    "bower.json"
  ],
  "extraDependencies": [
    "manifest.json",
    "bower_components/webcomponentsjs/webcomponents-lite.min.js"
  ],
  "builds": [{
    "preset": "es5-bundled"
  },{
    "preset": "es6-unbundled"
  }],
  "lint": {
    "rules": [
      "polymer-1"
    ]
  }
}
```

**Comment by milesje** [comment]
doing a unbundled build work fine.

**Comment by web-padawan** [comment]
What kind of error do you see?
BTW, es6 preset is not needed for 1.x

**Comment by milesje** [comment]
I know that es6 preset is not needed, I'm also working on coverting from 1.x to 2

**Comment by milesje** [comment]
```
error:   Promise rejection: Error: Failed to execute "git ls-remote --tags --heads https://github.com/PolymerElements/polymer.git", exit code of #128
remote: Repository not found.
fatal: repository 'https://github.com/PolymerElements/polymer.git/' not found

error:   Error: Failed to execute "git ls-remote --tags --heads https://github.com/PolymerElements/polymer.git", exit code of #128
remote: Repository not found.
fatal: repository 'https://github.com/PolymerElements/polymer.git/' not found

    at createError (C:\Users\jmiles\AppData\Roaming\nvm\v8.4.0\node_modules\polymer-cli\node_modules\bower\lib\util\createError.js:4:15)
    at ChildProcess.<anonymous> (C:\Users\jmiles\AppData\Roaming\nvm\v8.4.0\node_modules\polymer-cli\node_modules\bower\lib\util\cmd.js:102:21)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:545:12)
```

**Comment by milesje** [comment]
Updated CLI to 1.5.2 and still see errors.

**Comment by web-padawan** [comment]
Looks like a GitHub error but also try using node 6.11.2

Another reason to kick off bower BTW, it is much easier to use npm and private caching server, to stop depending on GitHub's downtime.

**Comment by milesje** [comment]
Build works with polymer-cli version <= 1.3.1 and fails with polymer-cli version >= 1.4.0

**Comment by milesje** [comment]
Changed to node 6.11.2 and polymer-cli 1.5.1 and the npm build still fails with the same error. But I think it may have something to do with a 3rd party bower resolver. We use the Nexus OSS repository to host our own private Bower, NPM, and Maven repository. The build succeeds if I don't install the nexus3-bower-resolver, but fails as soon as I do. If revert to polymer-cli 1.3.1 it works not matter if I have the nexus3-bower-resolver installed or not.
