### ISSUE TITLE
`polymer build` on app project throws errors

### ISSUE THREAD

**Issue by kaycebasques** [Polymer/polymer-cli#91]
I'm unclear as to how I'm supposed to use `polymer build` in combination with the app project. In the scenarios below, assume that I just initialized an app project. 

Scenario one: 

```
polymer build --entrypoint index.html
Could not uglify /Users/kayce/Desktop/test/bower_components/marked-element/demo/index.html_script_0.js
Could not uglify /Users/kayce/Desktop/test/bower_components/marked-element/test/marked-element.html_script_0.js
Could not uglify /Users/kayce/Desktop/test/bower_components/marked-element/test/marked-element.html_script_1.js
Could not uglify /Users/kayce/Desktop/test/bower_components/marked-element/test/marked-element.html_script_2.js
Could not uglify /Users/kayce/Desktop/test/bower_components/marked-element/test/marked-element.html_script_3.js
Could not uglify /Users/kayce/Desktop/test/bower_components/marked-element/test/marked-element.html_script_4.js
Could not uglify /Users/kayce/Desktop/test/bower_components/web-component-tester/data/index.html_script_0.js
Could not uglify /Users/kayce/Desktop/test/bower_components/web-component-tester/data/index.html_script_2.js
Promise rejection: TypeError: Cannot read property 'concat' of undefined
TypeError: Cannot read property 'concat' of undefined
    at _getBundles.then (/Users/kayce/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/lib/build/bundle.js:118:33)
    at run (/Users/kayce/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/node_modules/core-js/modules/es6.promise.js:89:22)
    at /Users/kayce/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/Users/kayce/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/node_modules/core-js/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Promise rejection: TypeError: Cannot read property 'concat' of undefined
TypeError: Cannot read property 'concat' of undefined
    at _getBundles.then (/Users/kayce/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/lib/build/bundle.js:118:33)
    at run (/Users/kayce/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/node_modules/core-js/modules/es6.promise.js:89:22)
    at /Users/kayce/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/Users/kayce/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/node_modules/core-js/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Scenario two: 

```
polymer build --main index.html
error Error: entrypoints must be specified
    at new StreamResolver (/Users/kayce/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/lib/build/stream-resolver.js:27:19)
    at new Bundler (/Users/kayce/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/lib/build/bundle.js:35:31)
    at Promise (/Users/kayce/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/lib/build/build.js:76:23)
    at new Promise (/Users/kayce/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/node_modules/core-js/modules/es6.promise.js:193:7)
    at Object.build (/Users/kayce/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/lib/build/build.js:32:12)
    at BuildCommand.run (/Users/kayce/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/lib/commands/build.js:45:24)
    at PolymerCli.run (/Users/kayce/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/lib/polymer-cli.js:54:17)
    at /Users/kayce/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/bin/polymer.js:21:7
    at /Users/kayce/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/node_modules/resolve/lib/async.js:46:14
    at process (/Users/kayce/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/node_modules/resolve/lib/async.js:173:43)
```

Scenario three:

```
polymer build --main index.html --entrypoint index.html
Could not uglify /Users/kayce/Desktop/test/bower_components/marked-element/demo/index.html_script_0.js
Could not uglify /Users/kayce/Desktop/test/bower_components/marked-element/test/marked-element.html_script_0.js
Could not uglify /Users/kayce/Desktop/test/bower_components/marked-element/test/marked-element.html_script_1.js
Could not uglify /Users/kayce/Desktop/test/bower_components/marked-element/test/marked-element.html_script_2.js
Could not uglify /Users/kayce/Desktop/test/bower_components/marked-element/test/marked-element.html_script_3.js
Could not uglify /Users/kayce/Desktop/test/bower_components/marked-element/test/marked-element.html_script_4.js
Could not uglify /Users/kayce/Desktop/test/bower_components/web-component-tester/data/index.html_script_0.js
Could not uglify /Users/kayce/Desktop/test/bower_components/web-component-tester/data/index.html_script_2.js
Promise rejection: TypeError: Cannot read property 'concat' of undefined
TypeError: Cannot read property 'concat' of undefined
    at _getBundles.then (/Users/kayce/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/lib/build/bundle.js:118:33)
    at run (/Users/kayce/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/node_modules/core-js/modules/es6.promise.js:89:22)
    at /Users/kayce/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/Users/kayce/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/node_modules/core-js/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Promise rejection: TypeError: Cannot read property 'concat' of undefined
TypeError: Cannot read property 'concat' of undefined
    at _getBundles.then (/Users/kayce/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/lib/build/bundle.js:118:33)
    at run (/Users/kayce/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/node_modules/core-js/modules/es6.promise.js:89:22)
    at /Users/kayce/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/Users/kayce/.nvm/versions/node/v6.0.0/lib/node_modules/polymer-cli/node_modules/core-js/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by azakus** [comment]
Closing for metabug #92
