### ISSUE TITLE
ASsertionError on new polymer-cli build

### ISSUE THREAD

**Issue by scottbarrow** [Polymer/polymer-cli#913]
### Description
polymer build fails with `AssertionError`

### Versions & Environment
- Polymer CLI:  0.18.1
- node: v8.7.0
- Operating System: 10.12.6 

#### Steps to Reproduce
1. install polymer-cli
2. run `polymer build`

#### Expected Results
3 builds

#### Actual Results
Error
``` cli runtime exception: AssertionError [ERR_ASSERTION]: Polymer Config Error: all "builds" require a "name" property when there are multiple builds defined.
error:   AssertionError [ERR_ASSERTION]: Polymer Config Error: all "builds" require a "name" property when there are multiple builds defined.
    at Console.assert (console.js:188:23)
    at ProjectConfig.validate (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-project-config/lib/index.js:236:29)
    at BuildCommand.<anonymous> (/usr/local/lib/node_modules/polymer-cli/lib/commands/build.js:100:20)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/polymer-cli/lib/commands/build.js:20:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/polymer-cli/lib/commands/build.js:16:12)
    at BuildCommand.run (/usr/local/lib/node_modules/polymer-cli/lib/commands/build.js:91:16)
    at PolymerCli.<anonymous> (/usr/local/lib/node_modules/polymer-cli/lib/polymer-cli.js:165:28)
    at Generator.next (<anonymous>)

**Comment by kumarargutech** [comment]
Hi Scottbarrow,

I will check in polymer.json file. I think "name" property missing in "builds" object collection in polymer.json file.

Once check your polymer.json file.

Sample "builds" object :

"builds": [
    {
      "name": "ES5 Bundled",
      "preset": "es5-bundled",
      "bundle": {
        "stripComments": true        
      },      
      "js" : {"minify": true},
      "css" : {"minify":true},
      "html" : {"minify": true},
      "addServiceWorker": true,
      "addPushManifest": true,
      "insertPrefetchLinks": true,
      "browserCapabilities": ["push","serviceworker"]      
    },
    {
      "name": "ES6 Bundled",
      "preset": "es6-bundled",
      "js" : {"minify": true},
      "css" : {"minify":true},
      "html" : {"minify": false},
      "addServiceWorker": true      
    },
    {
      "name": "ES6 Unbundled",
      "preset": "es6-unbundled",
      "js" : {"minify": true},
      "css" : {"minify":true},
      "html" : {"minify": true}      
    }
  ]


I hope,  it's helpful to you!

Thanks.
