### ISSUE TITLE
Issues when using a php entrypoint with a simple build

### ISSUE THREAD

**Issue by jsilvermist** [Polymer/polymer-cli#926]
### Description
When using a simple build with a `*.php` entrypoint, the build fails. If you use the exact same file but rename it to `*.html`, the build succeeds.

### Versions & Environment
- Polymer CLI: 1.5.7
- node: v8.4.0
- Operating System: Windows 10 version 1703 build 15063.726

#### Steps to Reproduce
Run:
```sh
git clone https://github.com/PolymerElements/polymer-starter-kit.git
cd polymer-starter-kit && bower install
```

Remove shell and fragments from `polymer.json`.
Run `polymer build`.
[Build completes successfully]

Rename `index.html` to `index.php`, change entrypoint in `polymer.json` to reflect new entrypoint.
Run `polymer build`.
[Build fails]

#### Thrown error message
```
C:\Users\Jason\Desktop\polymer-starter-kit>polymer build
info:    Clearing build\ directory...
info:    (es6-unbundled) Building...
error:   Promise rejection: Error: Unable to get document index.php: Document not found: index.php
error:   Error: Unable to get document index.php: Document not found: index.php
    at BuildAnalyzer.<anonymous> (C:\Users\Jason\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\polymer-build\lib\analyzer.js:323:23)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Jason\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\polymer-build\lib\analyzer.js:17:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

#### Note
Build seems to have completed successfully with php entrypoint while `shell` and `fragments` remained in `polymer.json`.

**Comment by kirilledelman** [comment]
I'm having deployment issues (`define is not defined`), a year later.
