### ISSUE TITLE
polymer init using polymer-2-starter-kit fails

### ISSUE THREAD

**Issue by c256985** [Polymer/polymer-cli#944]
### Description
Running the polymer init command using the polymer-2-starter-kit fails with this message.

info:    Running template polymer-2-starter-kit...
info:    Finding latest ^3.0.0 release of PolymerElements/polymer-starter-kit
error:   Uncaught exception: getaddrinfo ENOTFOUND 9000 9000:80
error:   Error: getaddrinfo ENOTFOUND 9000 9000:80
    at module.exports.__dirname.sendError (C:\Users\c256985\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\github\lib\index.js:838:19)
    at C:\Users\c256985\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\github\lib\index.js:849:29
    at callCallback (C:\Users\c256985\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\github\lib\index.js:713:17)
    at ClientRequest.<anonymous> (C:\Users\c256985\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\github\lib\index.js:791:17)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at emitErr (C:\Users\c256985\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\agent-base\agent.js:88:11)
    at C:\Users\c256985\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\agent-base\agent.js:99:9
    at Socket.onerror (C:\Users\c256985\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\https-proxy-agent\https-proxy-agent.js:104:5)
    at emitOne (events.js:115:13)

I'm not sure why it's trying to get a version 3 template for this.  I don't have any problem with the other templates.

### Versions & Environment

- Polymer CLI: 1.5.7
- node: 5.3.0
- Operating System: Windows/cygwin

#### Expected Results
No error is thrown, and the appropriate version of the template is used. In other words, I'm expecting it to use a polymer 2 template, not a polymer 3 template.

#### Actual Results
See previous error message

**Comment by jsilvermist** [comment]
PSK `3.0.0` is Polymer 2, not 3.

When a new starter kit is later released for Polymer 3, it will most likely be PSK `4.0.0`.

**Comment by c256985** [comment]
@jsilvermist That doesn't really explain the first part of the error message. "Finding latest ^3.0.0 release of PolymerElements/polymer-starter-kit". Unless there's no connection between the PSK release numbers and Polymer release numbers, and if that's the case, then things will get really confusing for developers.

**Comment by jsilvermist** [comment]
The starter kit version numbers don't equate to the version of Polymer used.

PolymerElements/polymer-starter-kit history:
`1.0.0`: Polymer 1, uses a large gulpfile, many gulp transforms.
`2.0.0`: Also Polymer 1, uses `polymer build`, contains `polymer.json` instead of gulpfile.
`3.0.0`: Polymer 2 version of version `2.0.0` using `polymer build`.
`4.0.0`: TBA! Will most likely be a Polymer 3 version of `3.0.0`.
